/**
 * @file autonomous_temporary.c
 *
 * @brief This source file was generated by cantools version 40.2.3 Sat Jul 26 00:48:02 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "autonomous_temporary.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int autonomous_temporary_acu_ms_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_acu_ms_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->mission_select, 0u, 0xffu);

    return (1);
}

int autonomous_temporary_acu_ms_unpack(
    struct autonomous_temporary_acu_ms_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->mission_select = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_acu_ms_init(struct autonomous_temporary_acu_ms_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_acu_ms_t));

    return 0;
}

uint8_t autonomous_temporary_acu_ms_mission_select_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ms_mission_select_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_acu_ms_mission_select_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_jetson_ms_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_jetson_ms_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->mission_select, 0u, 0xffu);

    return (1);
}

int autonomous_temporary_jetson_ms_unpack(
    struct autonomous_temporary_jetson_ms_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->mission_select = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_jetson_ms_init(struct autonomous_temporary_jetson_ms_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_jetson_ms_t));

    return 0;
}

uint8_t autonomous_temporary_jetson_ms_mission_select_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_ms_mission_select_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_jetson_ms_mission_select_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_rpm_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_rpm_t *src_p,
    size_t size)
{
    uint16_t rpm;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    rpm = (uint16_t)src_p->rpm;
    dst_p[0] |= pack_left_shift_u16(rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(rpm, 8u, 0xffu);

    return (2);
}

int autonomous_temporary_vcu_rpm_unpack(
    struct autonomous_temporary_vcu_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rpm;

    if (size < 2u) {
        return (-EINVAL);
    }

    rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rpm = (int16_t)rpm;

    return (0);
}

int autonomous_temporary_vcu_rpm_init(struct autonomous_temporary_vcu_rpm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_rpm_t));

    return 0;
}

int16_t autonomous_temporary_vcu_rpm_rpm_encode(double value)
{
    return (int16_t)(value);
}

double autonomous_temporary_vcu_rpm_rpm_decode(int16_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_rpm_rpm_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 6000));
}

int autonomous_temporary_target_rpm_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_target_rpm_t *src_p,
    size_t size)
{
    uint8_t steering_angle_actual;
    uint8_t steering_angle_target;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->speed_actual, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->speed_target, 0u, 0xffu);
    steering_angle_actual = (uint8_t)src_p->steering_angle_actual;
    dst_p[2] |= pack_left_shift_u8(steering_angle_actual, 0u, 0xffu);
    steering_angle_target = (uint8_t)src_p->steering_angle_target;
    dst_p[3] |= pack_left_shift_u8(steering_angle_target, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_target_rpm_unpack(
    struct autonomous_temporary_target_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t steering_angle_actual;
    uint8_t steering_angle_target;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->speed_actual = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->speed_target = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    steering_angle_actual = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->steering_angle_actual = (int8_t)steering_angle_actual;
    steering_angle_target = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->steering_angle_target = (int8_t)steering_angle_target;

    return (0);
}

int autonomous_temporary_target_rpm_init(struct autonomous_temporary_target_rpm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_target_rpm_t));

    return 0;
}

uint8_t autonomous_temporary_target_rpm_speed_actual_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double autonomous_temporary_target_rpm_speed_actual_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool autonomous_temporary_target_rpm_speed_actual_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_target_rpm_speed_target_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double autonomous_temporary_target_rpm_speed_target_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool autonomous_temporary_target_rpm_speed_target_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int8_t autonomous_temporary_target_rpm_steering_angle_actual_encode(double value)
{
    return (int8_t)(value / 0.5);
}

double autonomous_temporary_target_rpm_steering_angle_actual_decode(int8_t value)
{
    return ((double)value * 0.5);
}

bool autonomous_temporary_target_rpm_steering_angle_actual_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t autonomous_temporary_target_rpm_steering_angle_target_encode(double value)
{
    return (int8_t)(value / 0.5);
}

double autonomous_temporary_target_rpm_steering_angle_target_decode(int8_t value)
{
    return ((double)value * 0.5);
}

bool autonomous_temporary_target_rpm_steering_angle_target_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_acu_ign_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_acu_ign_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->ign, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->asms, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->emergency, 0u, 0xffu);

    return (5);
}

int autonomous_temporary_acu_ign_unpack(
    struct autonomous_temporary_acu_ign_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->ign = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->asms = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->emergency = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_acu_ign_init(struct autonomous_temporary_acu_ign_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_acu_ign_t));

    return 0;
}

uint8_t autonomous_temporary_acu_ign_ign_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ign_ign_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_acu_ign_ign_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t autonomous_temporary_acu_ign_asms_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ign_asms_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_acu_ign_asms_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t autonomous_temporary_acu_ign_emergency_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ign_emergency_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_acu_ign_emergency_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_rd_jetson_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_rd_jetson_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rd, 0u, 0xffu);

    return (1);
}

int autonomous_temporary_rd_jetson_unpack(
    struct autonomous_temporary_rd_jetson_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_rd_jetson_init(struct autonomous_temporary_rd_jetson_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_rd_jetson_t));

    return 0;
}

uint8_t autonomous_temporary_rd_jetson_rd_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_rd_jetson_rd_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_rd_jetson_rd_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_as_state_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_as_state_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->state, 0u, 0xffu);

    return (1);
}

int autonomous_temporary_as_state_unpack(
    struct autonomous_temporary_as_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_as_state_init(struct autonomous_temporary_as_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_as_state_t));

    return 0;
}

uint8_t autonomous_temporary_as_state_state_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_as_state_state_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_as_state_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_hv_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_hv_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->hv, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->brake_pressure_front, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_pressure_rear, 0u, 0xffu);

    return (3);
}

int autonomous_temporary_vcu_hv_unpack(
    struct autonomous_temporary_vcu_hv_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->hv = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->brake_pressure_front = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake_pressure_rear = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_vcu_hv_init(struct autonomous_temporary_vcu_hv_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_hv_t));

    return 0;
}

uint8_t autonomous_temporary_vcu_hv_hv_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_hv_hv_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_hv_hv_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_hv_brake_pressure_front_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_hv_brake_pressure_front_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_hv_brake_pressure_front_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_hv_brake_pressure_rear_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_hv_brake_pressure_rear_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_hv_brake_pressure_rear_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_res_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->signal, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_res_unpack(
    struct autonomous_temporary_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_res_init(struct autonomous_temporary_res_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_res_t));

    return 0;
}

uint8_t autonomous_temporary_res_signal_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_res_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_res_signal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_dyn_f_sig1_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dyn_f_sig1_t *src_p,
    size_t size)
{
    uint16_t st_angle;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    st_angle = (uint16_t)src_p->st_angle;
    dst_p[0] |= pack_left_shift_u16(st_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(st_angle, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->susp_r, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->susp_r, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->susp_l, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->susp_l, 8u, 0xffu);

    return (6);
}

int autonomous_temporary_dyn_f_sig1_unpack(
    struct autonomous_temporary_dyn_f_sig1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t st_angle;

    if (size < 6u) {
        return (-EINVAL);
    }

    st_angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    st_angle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->st_angle = (int16_t)st_angle;
    dst_p->susp_r = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->susp_r |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->susp_l = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->susp_l |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_dyn_f_sig1_init(struct autonomous_temporary_dyn_f_sig1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dyn_f_sig1_t));

    return 0;
}

int16_t autonomous_temporary_dyn_f_sig1_st_angle_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double autonomous_temporary_dyn_f_sig1_st_angle_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_f_sig1_st_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_f_sig1_susp_r_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_f_sig1_susp_r_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_f_sig1_susp_r_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_f_sig1_susp_l_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_f_sig1_susp_l_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_f_sig1_susp_l_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_dyn_f_sig2_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dyn_f_sig2_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->spd_left, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->spd_left, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->spd_right, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->spd_right, 8u, 0xffu);

    return (4);
}

int autonomous_temporary_dyn_f_sig2_unpack(
    struct autonomous_temporary_dyn_f_sig2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->spd_left = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->spd_left |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->spd_right = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->spd_right |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_dyn_f_sig2_init(struct autonomous_temporary_dyn_f_sig2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dyn_f_sig2_t));

    return 0;
}

uint16_t autonomous_temporary_dyn_f_sig2_spd_left_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_f_sig2_spd_left_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_f_sig2_spd_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_f_sig2_spd_right_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_f_sig2_spd_right_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_f_sig2_spd_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_dyn_r_sig1_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dyn_r_sig1_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->brk_press, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->brk_press, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->susp_r, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->susp_r, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->susp_l, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->susp_l, 8u, 0xffu);

    return (6);
}

int autonomous_temporary_dyn_r_sig1_unpack(
    struct autonomous_temporary_dyn_r_sig1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->brk_press = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->brk_press |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->susp_r = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->susp_r |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->susp_l = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->susp_l |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_dyn_r_sig1_init(struct autonomous_temporary_dyn_r_sig1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dyn_r_sig1_t));

    return 0;
}

uint16_t autonomous_temporary_dyn_r_sig1_brk_press_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_r_sig1_brk_press_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_r_sig1_brk_press_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_r_sig1_susp_r_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_r_sig1_susp_r_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_r_sig1_susp_r_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_r_sig1_susp_l_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_r_sig1_susp_l_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_r_sig1_susp_l_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_dyn_r_sig2_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dyn_r_sig2_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->spd_left, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->spd_left, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->spd_right, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->spd_right, 8u, 0xffu);

    return (4);
}

int autonomous_temporary_dyn_r_sig2_unpack(
    struct autonomous_temporary_dyn_r_sig2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->spd_left = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->spd_left |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->spd_right = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->spd_right |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_dyn_r_sig2_init(struct autonomous_temporary_dyn_r_sig2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dyn_r_sig2_t));

    return 0;
}

uint16_t autonomous_temporary_dyn_r_sig2_spd_left_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_r_sig2_spd_left_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_r_sig2_spd_left_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_r_sig2_spd_right_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_r_sig2_spd_right_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_r_sig2_spd_right_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_asf_signals_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_asf_signals_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->ebs_pressure_tank_front, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ebs_pressure_tank_rear, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_pressure_front, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_pressure_rear, 0u, 0xffu);

    return (4);
}

int autonomous_temporary_asf_signals_unpack(
    struct autonomous_temporary_asf_signals_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->ebs_pressure_tank_front = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ebs_pressure_tank_rear = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake_pressure_front = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->brake_pressure_rear = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_asf_signals_init(struct autonomous_temporary_asf_signals_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_asf_signals_t));

    return 0;
}

uint8_t autonomous_temporary_asf_signals_ebs_pressure_tank_front_encode(double value)
{
    return (uint8_t)(value / 10.0);
}

double autonomous_temporary_asf_signals_ebs_pressure_tank_front_decode(uint8_t value)
{
    return ((double)value * 10.0);
}

bool autonomous_temporary_asf_signals_ebs_pressure_tank_front_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_asf_signals_ebs_pressure_tank_rear_encode(double value)
{
    return (uint8_t)(value / 10.0);
}

double autonomous_temporary_asf_signals_ebs_pressure_tank_rear_decode(uint8_t value)
{
    return ((double)value * 10.0);
}

bool autonomous_temporary_asf_signals_ebs_pressure_tank_rear_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_asf_signals_brake_pressure_front_encode(double value)
{
    return (uint8_t)(value / 10.0);
}

double autonomous_temporary_asf_signals_brake_pressure_front_decode(uint8_t value)
{
    return ((double)value * 10.0);
}

bool autonomous_temporary_asf_signals_brake_pressure_front_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_asf_signals_brake_pressure_rear_encode(double value)
{
    return (uint8_t)(value / 10.0);
}

double autonomous_temporary_asf_signals_brake_pressure_rear_decode(uint8_t value)
{
    return ((double)value * 10.0);
}

bool autonomous_temporary_asf_signals_brake_pressure_rear_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_ign_r2_d_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_ign_r2_d_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ignition_manual, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->r2d_manual, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->ignition_auto, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->r2d_auto, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_vcu_ign_r2_d_unpack(
    struct autonomous_temporary_vcu_ign_r2_d_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ignition_manual = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->r2d_manual = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->ignition_auto = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->r2d_auto = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_vcu_ign_r2_d_init(struct autonomous_temporary_vcu_ign_r2_d_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_ign_r2_d_t));

    return 0;
}

uint8_t autonomous_temporary_vcu_ign_r2_d_ignition_manual_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_ignition_manual_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_ignition_manual_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_r2d_manual_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_r2d_manual_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_r2d_manual_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_ignition_auto_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_ignition_auto_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_ignition_auto_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_r2d_auto_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_r2d_auto_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_r2d_auto_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
