/**
 * @file autonomous_temporary.c
 *
 * @brief This source file was generated by cantools version 40.3.0 Thu Aug  7 22:38:22 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "autonomous_temporary.h"

#include <string.h>

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask) {
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int autonomous_temporary_acu_ms_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_acu_ms_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->mission_select, 0u, 0xffu);

    return (1);
}

int autonomous_temporary_acu_ms_unpack(
    struct autonomous_temporary_acu_ms_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->mission_select = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_acu_ms_init(struct autonomous_temporary_acu_ms_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_acu_ms_t));

    return 0;
}

uint8_t autonomous_temporary_acu_ms_mission_select_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ms_mission_select_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_acu_ms_mission_select_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_jetson_ms_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_jetson_ms_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->mission_select, 0u, 0xffu);

    return (1);
}

int autonomous_temporary_jetson_ms_unpack(
    struct autonomous_temporary_jetson_ms_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->mission_select = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_jetson_ms_init(struct autonomous_temporary_jetson_ms_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_jetson_ms_t));

    return 0;
}

uint8_t autonomous_temporary_jetson_ms_mission_select_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_ms_mission_select_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_jetson_ms_mission_select_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_rpm_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_rpm_t *src_p,
    size_t size) {
    uint16_t rpm_actual;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    rpm_actual = (uint16_t)src_p->rpm_actual;
    dst_p[0] |= pack_left_shift_u16(rpm_actual, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(rpm_actual, 8u, 0xffu);

    return (2);
}

int autonomous_temporary_vcu_rpm_unpack(
    struct autonomous_temporary_vcu_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    uint16_t rpm_actual;

    if (size < 2u) {
        return (-EINVAL);
    }

    rpm_actual = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    rpm_actual |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rpm_actual = (int16_t)rpm_actual;

    return (0);
}

int autonomous_temporary_vcu_rpm_init(struct autonomous_temporary_vcu_rpm_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_rpm_t));

    return 0;
}

int16_t autonomous_temporary_vcu_rpm_rpm_actual_encode(double value) {
    return (int16_t)(value);
}

double autonomous_temporary_vcu_rpm_rpm_actual_decode(int16_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_rpm_rpm_actual_is_in_range(int16_t value) {
    return ((value >= 0) && (value <= 6000));
}

int autonomous_temporary_dl_msg_1_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dl_msg_1_t *src_p,
    size_t size) {
    uint8_t steering_angle_actual;
    uint8_t steering_angle_target;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->speed_actual, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->speed_target, 0u, 0xffu);
    steering_angle_actual = (uint8_t)src_p->steering_angle_actual;
    dst_p[2] |= pack_left_shift_u8(steering_angle_actual, 0u, 0xffu);
    steering_angle_target = (uint8_t)src_p->steering_angle_target;
    dst_p[3] |= pack_left_shift_u8(steering_angle_target, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_dl_msg_1_unpack(
    struct autonomous_temporary_dl_msg_1_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    uint8_t steering_angle_actual;
    uint8_t steering_angle_target;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->speed_actual = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->speed_target = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    steering_angle_actual = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->steering_angle_actual = (int8_t)steering_angle_actual;
    steering_angle_target = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->steering_angle_target = (int8_t)steering_angle_target;

    return (0);
}

int autonomous_temporary_dl_msg_1_init(struct autonomous_temporary_dl_msg_1_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dl_msg_1_t));

    return 0;
}

uint8_t autonomous_temporary_dl_msg_1_speed_actual_encode(double value) {
    return (uint8_t)(value / 0.5);
}

double autonomous_temporary_dl_msg_1_speed_actual_decode(uint8_t value) {
    return ((double)value * 0.5);
}

bool autonomous_temporary_dl_msg_1_speed_actual_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_dl_msg_1_speed_target_encode(double value) {
    return (uint8_t)(value / 0.5);
}

double autonomous_temporary_dl_msg_1_speed_target_decode(uint8_t value) {
    return ((double)value * 0.5);
}

bool autonomous_temporary_dl_msg_1_speed_target_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int8_t autonomous_temporary_dl_msg_1_steering_angle_actual_encode(double value) {
    return (int8_t)(value / 0.5);
}

double autonomous_temporary_dl_msg_1_steering_angle_actual_decode(int8_t value) {
    return ((double)value * 0.5);
}

bool autonomous_temporary_dl_msg_1_steering_angle_actual_is_in_range(int8_t value) {
    (void)value;

    return (true);
}

int8_t autonomous_temporary_dl_msg_1_steering_angle_target_encode(double value) {
    return (int8_t)(value / 0.5);
}

double autonomous_temporary_dl_msg_1_steering_angle_target_decode(int8_t value) {
    return ((double)value * 0.5);
}

bool autonomous_temporary_dl_msg_1_steering_angle_target_is_in_range(int8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_acu_ign_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_acu_ign_t *src_p,
    size_t size) {
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->ign, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->asms, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->emergency, 0u, 0xffu);

    return (5);
}

int autonomous_temporary_acu_ign_unpack(
    struct autonomous_temporary_acu_ign_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->ign = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->asms = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->emergency = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_acu_ign_init(struct autonomous_temporary_acu_ign_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_acu_ign_t));

    return 0;
}

uint8_t autonomous_temporary_acu_ign_ign_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ign_ign_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_acu_ign_ign_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t autonomous_temporary_acu_ign_asms_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ign_asms_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_acu_ign_asms_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t autonomous_temporary_acu_ign_emergency_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ign_emergency_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_acu_ign_emergency_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_rd_jetson_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_rd_jetson_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rd, 0u, 0xffu);

    return (1);
}

int autonomous_temporary_rd_jetson_unpack(
    struct autonomous_temporary_rd_jetson_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_rd_jetson_init(struct autonomous_temporary_rd_jetson_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_rd_jetson_t));

    return 0;
}

uint8_t autonomous_temporary_rd_jetson_rd_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_rd_jetson_rd_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_rd_jetson_rd_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_as_state_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_as_state_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->state, 0u, 0xffu);

    return (1);
}

int autonomous_temporary_as_state_unpack(
    struct autonomous_temporary_as_state_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_as_state_init(struct autonomous_temporary_as_state_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_as_state_t));

    return 0;
}

uint8_t autonomous_temporary_as_state_state_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_as_state_state_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_as_state_state_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_hv_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_hv_t *src_p,
    size_t size) {
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->hv, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->brake_pressure_front, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_pressure_rear, 0u, 0xffu);

    return (3);
}

int autonomous_temporary_vcu_hv_unpack(
    struct autonomous_temporary_vcu_hv_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->hv = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->brake_pressure_front = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake_pressure_rear = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_vcu_hv_init(struct autonomous_temporary_vcu_hv_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_hv_t));

    return 0;
}

uint8_t autonomous_temporary_vcu_hv_hv_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_hv_hv_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_hv_hv_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_hv_brake_pressure_front_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_hv_brake_pressure_front_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_hv_brake_pressure_front_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_hv_brake_pressure_rear_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_hv_brake_pressure_rear_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_hv_brake_pressure_rear_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_res_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_res_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->signal, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_res_unpack(
    struct autonomous_temporary_res_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_res_init(struct autonomous_temporary_res_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_res_t));

    return 0;
}

uint8_t autonomous_temporary_res_signal_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_res_signal_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_res_signal_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_dyn_front_sig1_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dyn_front_sig1_t *src_p,
    size_t size) {
    uint16_t st_angle;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    st_angle = (uint16_t)src_p->st_angle;
    dst_p[0] |= pack_left_shift_u16(st_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(st_angle, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->susp_r, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->susp_r, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->susp_l, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->susp_l, 8u, 0xffu);

    return (6);
}

int autonomous_temporary_dyn_front_sig1_unpack(
    struct autonomous_temporary_dyn_front_sig1_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    uint16_t st_angle;

    if (size < 6u) {
        return (-EINVAL);
    }

    st_angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    st_angle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->st_angle = (int16_t)st_angle;
    dst_p->susp_r = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->susp_r |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->susp_l = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->susp_l |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_dyn_front_sig1_init(struct autonomous_temporary_dyn_front_sig1_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dyn_front_sig1_t));

    return 0;
}

int16_t autonomous_temporary_dyn_front_sig1_st_angle_encode(double value) {
    return (int16_t)(value / 0.1);
}

double autonomous_temporary_dyn_front_sig1_st_angle_decode(int16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_front_sig1_st_angle_is_in_range(int16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_front_sig1_susp_r_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_front_sig1_susp_r_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_front_sig1_susp_r_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_front_sig1_susp_l_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_front_sig1_susp_l_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_front_sig1_susp_l_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_dyn_front_sig2_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dyn_front_sig2_t *src_p,
    size_t size) {
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->spd_left, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->spd_left, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->spd_right, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->spd_right, 8u, 0xffu);

    return (4);
}

int autonomous_temporary_dyn_front_sig2_unpack(
    struct autonomous_temporary_dyn_front_sig2_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->spd_left = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->spd_left |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->spd_right = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->spd_right |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_dyn_front_sig2_init(struct autonomous_temporary_dyn_front_sig2_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dyn_front_sig2_t));

    return 0;
}

uint16_t autonomous_temporary_dyn_front_sig2_spd_left_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_front_sig2_spd_left_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_front_sig2_spd_left_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_front_sig2_spd_right_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_front_sig2_spd_right_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_front_sig2_spd_right_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_dyn_rear_sig1_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dyn_rear_sig1_t *src_p,
    size_t size) {
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->brk_press, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->brk_press, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->susp_r, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->susp_r, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->susp_l, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->susp_l, 8u, 0xffu);

    return (6);
}

int autonomous_temporary_dyn_rear_sig1_unpack(
    struct autonomous_temporary_dyn_rear_sig1_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->brk_press = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->brk_press |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->susp_r = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->susp_r |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->susp_l = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->susp_l |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_dyn_rear_sig1_init(struct autonomous_temporary_dyn_rear_sig1_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dyn_rear_sig1_t));

    return 0;
}

uint16_t autonomous_temporary_dyn_rear_sig1_brk_press_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_rear_sig1_brk_press_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_rear_sig1_brk_press_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_rear_sig1_susp_r_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_rear_sig1_susp_r_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_rear_sig1_susp_r_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_rear_sig1_susp_l_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_rear_sig1_susp_l_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_rear_sig1_susp_l_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_dyn_rear_sig2_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_dyn_rear_sig2_t *src_p,
    size_t size) {
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->spd_left, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->spd_left, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->spd_right, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->spd_right, 8u, 0xffu);

    return (4);
}

int autonomous_temporary_dyn_rear_sig2_unpack(
    struct autonomous_temporary_dyn_rear_sig2_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->spd_left = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->spd_left |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->spd_right = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->spd_right |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_dyn_rear_sig2_init(struct autonomous_temporary_dyn_rear_sig2_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_dyn_rear_sig2_t));

    return 0;
}

uint16_t autonomous_temporary_dyn_rear_sig2_spd_left_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_rear_sig2_spd_left_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_rear_sig2_spd_left_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_dyn_rear_sig2_spd_right_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_dyn_rear_sig2_spd_right_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_dyn_rear_sig2_spd_right_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_asf_signals_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_asf_signals_t *src_p,
    size_t size) {
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->ebs_pressure_tank_front, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ebs_pressure_tank_rear, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_pressure_front, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_pressure_rear, 0u, 0xffu);

    return (4);
}

int autonomous_temporary_asf_signals_unpack(
    struct autonomous_temporary_asf_signals_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->ebs_pressure_tank_front = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ebs_pressure_tank_rear = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake_pressure_front = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->brake_pressure_rear = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_asf_signals_init(struct autonomous_temporary_asf_signals_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_asf_signals_t));

    return 0;
}

uint8_t autonomous_temporary_asf_signals_ebs_pressure_tank_front_encode(double value) {
    return (uint8_t)(value / 10.0);
}

double autonomous_temporary_asf_signals_ebs_pressure_tank_front_decode(uint8_t value) {
    return ((double)value * 10.0);
}

bool autonomous_temporary_asf_signals_ebs_pressure_tank_front_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_asf_signals_ebs_pressure_tank_rear_encode(double value) {
    return (uint8_t)(value / 10.0);
}

double autonomous_temporary_asf_signals_ebs_pressure_tank_rear_decode(uint8_t value) {
    return ((double)value * 10.0);
}

bool autonomous_temporary_asf_signals_ebs_pressure_tank_rear_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_asf_signals_brake_pressure_front_encode(double value) {
    return (uint8_t)(value / 10.0);
}

double autonomous_temporary_asf_signals_brake_pressure_front_decode(uint8_t value) {
    return ((double)value * 10.0);
}

bool autonomous_temporary_asf_signals_brake_pressure_front_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_asf_signals_brake_pressure_rear_encode(double value) {
    return (uint8_t)(value / 10.0);
}

double autonomous_temporary_asf_signals_brake_pressure_rear_decode(uint8_t value) {
    return ((double)value * 10.0);
}

bool autonomous_temporary_asf_signals_brake_pressure_rear_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_ign_r2_d_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_ign_r2_d_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ignition_manual, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->r2d_manual, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->ignition_auto, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->r2d_auto, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->shutdown_signal, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->vcu_state, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->r2_d_button_raw, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->ignition_switch_raw, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_vcu_ign_r2_d_unpack(
    struct autonomous_temporary_vcu_ign_r2_d_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ignition_manual = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->r2d_manual = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->ignition_auto = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->r2d_auto = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->shutdown_signal = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->vcu_state = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->r2_d_button_raw = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->ignition_switch_raw = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_vcu_ign_r2_d_init(struct autonomous_temporary_vcu_ign_r2_d_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_ign_r2_d_t));

    return 0;
}

uint8_t autonomous_temporary_vcu_ign_r2_d_ignition_manual_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_ignition_manual_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_ignition_manual_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_r2d_manual_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_r2d_manual_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_r2d_manual_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_ignition_auto_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_ignition_auto_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_ignition_auto_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_r2d_auto_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_r2d_auto_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_r2d_auto_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_shutdown_signal_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_shutdown_signal_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_shutdown_signal_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_vcu_state_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_vcu_state_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_vcu_state_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_r2_d_button_raw_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_r2_d_button_raw_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_r2_d_button_raw_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_ign_r2_d_ignition_switch_raw_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_ign_r2_d_ignition_switch_raw_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_ign_r2_d_ignition_switch_raw_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_acu_status_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_acu_status_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->acu_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->assi_state, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->internal_temperature, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_acu_status_unpack(
    struct autonomous_temporary_acu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->acu_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->assi_state = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->internal_temperature = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_acu_status_init(struct autonomous_temporary_acu_status_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_acu_status_t));

    return 0;
}

uint8_t autonomous_temporary_acu_status_acu_state_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_acu_status_acu_state_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_acu_status_acu_state_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_acu_status_assi_state_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_acu_status_assi_state_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_acu_status_assi_state_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_acu_status_internal_temperature_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_acu_status_internal_temperature_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_acu_status_internal_temperature_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_apps_raw_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_apps_raw_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->apps_1_raw_bits, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->apps_2_raw_bits, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->delta_raw, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->cpu_temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->flag_digital_bspd, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->apps_error_type, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->apps_1000, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->apps_1000, 8u, 0xffu);

    return (8);
}

int autonomous_temporary_vcu_apps_raw_unpack(
    struct autonomous_temporary_vcu_apps_raw_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->apps_1_raw_bits = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->apps_2_raw_bits = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->delta_raw = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->cpu_temp = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->flag_digital_bspd = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->apps_error_type = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->apps_1000 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->apps_1000 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_vcu_apps_raw_init(struct autonomous_temporary_vcu_apps_raw_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_apps_raw_t));

    return 0;
}

uint8_t autonomous_temporary_vcu_apps_raw_apps_1_raw_bits_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_apps_raw_apps_1_raw_bits_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_apps_raw_apps_1_raw_bits_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_apps_raw_apps_2_raw_bits_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_apps_raw_apps_2_raw_bits_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_apps_raw_apps_2_raw_bits_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_apps_raw_delta_raw_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_apps_raw_delta_raw_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_apps_raw_delta_raw_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_apps_raw_cpu_temp_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_apps_raw_cpu_temp_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_apps_raw_cpu_temp_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_apps_raw_flag_digital_bspd_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_apps_raw_flag_digital_bspd_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_apps_raw_flag_digital_bspd_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_vcu_apps_raw_apps_error_type_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_apps_raw_apps_error_type_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_apps_raw_apps_error_type_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_vcu_apps_raw_apps_1000_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_vcu_apps_raw_apps_1000_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_vcu_apps_raw_apps_1000_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_rpm_target_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_rpm_target_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm_target, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm_target, 8u, 0xffu);

    return (8);
}

int autonomous_temporary_rpm_target_unpack(
    struct autonomous_temporary_rpm_target_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm_target = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm_target |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_rpm_target_init(struct autonomous_temporary_rpm_target_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_rpm_target_t));

    return 0;
}

uint16_t autonomous_temporary_rpm_target_rpm_target_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_rpm_target_rpm_target_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_rpm_target_rpm_target_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_jetson_debug_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_jetson_debug_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->pos_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pos_x, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pos_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pos_y, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->temperature, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_jetson_debug_unpack(
    struct autonomous_temporary_jetson_debug_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->pos_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pos_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pos_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pos_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temperature = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_jetson_debug_init(struct autonomous_temporary_jetson_debug_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_jetson_debug_t));

    return 0;
}

uint16_t autonomous_temporary_jetson_debug_pos_x_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_jetson_debug_pos_x_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_jetson_debug_pos_x_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_jetson_debug_pos_y_encode(double value) {
    return (uint16_t)(value / 0.1);
}

double autonomous_temporary_jetson_debug_pos_y_decode(uint16_t value) {
    return ((double)value * 0.1);
}

bool autonomous_temporary_jetson_debug_pos_y_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_jetson_debug_temperature_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_debug_temperature_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_jetson_debug_temperature_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_jetson_data_1_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_jetson_data_1_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->target_angle, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->target_speed, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->actual_angle, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->actual_speed, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->lap_count, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->current_cone_count, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->total_cone_count, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_jetson_data_1_unpack(
    struct autonomous_temporary_jetson_data_1_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->target_angle = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->target_speed = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->actual_angle = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->actual_speed = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->lap_count = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->current_cone_count = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->total_cone_count = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_jetson_data_1_init(struct autonomous_temporary_jetson_data_1_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_jetson_data_1_t));

    return 0;
}

uint8_t autonomous_temporary_jetson_data_1_target_angle_encode(double value) {
    return (uint8_t)(value / 0.5);
}

double autonomous_temporary_jetson_data_1_target_angle_decode(uint8_t value) {
    return ((double)value * 0.5);
}

bool autonomous_temporary_jetson_data_1_target_angle_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_jetson_data_1_target_speed_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_data_1_target_speed_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_jetson_data_1_target_speed_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_jetson_data_1_actual_angle_encode(double value) {
    return (uint8_t)(value / 0.5);
}

double autonomous_temporary_jetson_data_1_actual_angle_decode(uint8_t value) {
    return ((double)value * 0.5);
}

bool autonomous_temporary_jetson_data_1_actual_angle_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_jetson_data_1_actual_speed_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_data_1_actual_speed_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_jetson_data_1_actual_speed_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_jetson_data_1_lap_count_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_data_1_lap_count_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_jetson_data_1_lap_count_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_jetson_data_1_current_cone_count_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_data_1_current_cone_count_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_jetson_data_1_current_cone_count_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t autonomous_temporary_jetson_data_1_total_cone_count_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_data_1_total_cone_count_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_jetson_data_1_total_cone_count_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_maxon_mode_rx_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_maxon_mode_rx_t *src_p,
    size_t size) {
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->control_word, 0u, 0xffu);

    return (2);
}

int autonomous_temporary_maxon_mode_rx_unpack(
    struct autonomous_temporary_maxon_mode_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->control_word = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_maxon_mode_rx_init(struct autonomous_temporary_maxon_mode_rx_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_maxon_mode_rx_t));

    return 0;
}

uint8_t autonomous_temporary_maxon_mode_rx_control_word_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_maxon_mode_rx_control_word_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_mode_rx_control_word_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_maxon_position_rx_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_maxon_position_rx_t *src_p,
    size_t size) {
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->control_word, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->target_position, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->target_position, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->target_position, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->target_position, 24u, 0xffu);

    return (6);
}

int autonomous_temporary_maxon_position_rx_unpack(
    struct autonomous_temporary_maxon_position_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->control_word = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->target_position = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->target_position |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->target_position |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->target_position |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);

    return (0);
}

int autonomous_temporary_maxon_position_rx_init(struct autonomous_temporary_maxon_position_rx_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_maxon_position_rx_t));

    return 0;
}

uint8_t autonomous_temporary_maxon_position_rx_control_word_encode(double value) {
    return (uint8_t)(value);
}

double autonomous_temporary_maxon_position_rx_control_word_decode(uint8_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_position_rx_control_word_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint32_t autonomous_temporary_maxon_position_rx_target_position_encode(double value) {
    return (uint32_t)(value);
}

double autonomous_temporary_maxon_position_rx_target_position_decode(uint32_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_position_rx_target_position_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_maxon_profile_rx_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_maxon_profile_rx_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->profile_velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->profile_velocity, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->profile_velocity, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->profile_velocity, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->profile_acceleration, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->profile_acceleration, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->profile_acceleration, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->profile_acceleration, 24u, 0xffu);

    return (8);
}

int autonomous_temporary_maxon_profile_rx_unpack(
    struct autonomous_temporary_maxon_profile_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->profile_velocity = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->profile_velocity |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->profile_velocity |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->profile_velocity |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->profile_acceleration = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->profile_acceleration |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->profile_acceleration |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->profile_acceleration |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int autonomous_temporary_maxon_profile_rx_init(struct autonomous_temporary_maxon_profile_rx_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_maxon_profile_rx_t));

    return 0;
}

uint32_t autonomous_temporary_maxon_profile_rx_profile_velocity_encode(double value) {
    return (uint32_t)(value);
}

double autonomous_temporary_maxon_profile_rx_profile_velocity_decode(uint32_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_profile_rx_profile_velocity_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

uint32_t autonomous_temporary_maxon_profile_rx_profile_acceleration_encode(double value) {
    return (uint32_t)(value);
}

double autonomous_temporary_maxon_profile_rx_profile_acceleration_decode(uint32_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_profile_rx_profile_acceleration_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_maxon_status_tx_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_maxon_status_tx_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->status_word, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->status_word, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->control_word, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->control_word, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->current_actual_value, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->current_actual_value, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->current_actual_value, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->current_actual_value, 24u, 0xffu);

    return (8);
}

int autonomous_temporary_maxon_status_tx_unpack(
    struct autonomous_temporary_maxon_status_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status_word = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->status_word |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->control_word = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->control_word |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_actual_value = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->current_actual_value |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->current_actual_value |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->current_actual_value |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int autonomous_temporary_maxon_status_tx_init(struct autonomous_temporary_maxon_status_tx_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_maxon_status_tx_t));

    return 0;
}

uint16_t autonomous_temporary_maxon_status_tx_status_word_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_maxon_status_tx_status_word_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_status_tx_status_word_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_maxon_status_tx_control_word_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_maxon_status_tx_control_word_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_status_tx_control_word_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint32_t autonomous_temporary_maxon_status_tx_current_actual_value_encode(double value) {
    return (uint32_t)(value);
}

double autonomous_temporary_maxon_status_tx_current_actual_value_decode(uint32_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_status_tx_current_actual_value_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_maxon_status2_tx_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_maxon_status2_tx_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->error_code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->error_code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->status_word, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->status_word, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->current_average_value, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->current_average_value, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->current_average_value, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->current_average_value, 24u, 0xffu);

    return (8);
}

int autonomous_temporary_maxon_status2_tx_unpack(
    struct autonomous_temporary_maxon_status2_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->error_code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->error_code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->status_word = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->status_word |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_average_value = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->current_average_value |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->current_average_value |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->current_average_value |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int autonomous_temporary_maxon_status2_tx_init(struct autonomous_temporary_maxon_status2_tx_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_maxon_status2_tx_t));

    return 0;
}

uint16_t autonomous_temporary_maxon_status2_tx_error_code_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_maxon_status2_tx_error_code_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_status2_tx_error_code_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_maxon_status2_tx_status_word_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_maxon_status2_tx_status_word_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_status2_tx_status_word_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint32_t autonomous_temporary_maxon_status2_tx_current_average_value_encode(double value) {
    return (uint32_t)(value);
}

double autonomous_temporary_maxon_status2_tx_current_average_value_decode(uint32_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_status2_tx_current_average_value_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_maxon_position_tx_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_maxon_position_tx_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->status_word, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->status_word, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->actual_position, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->actual_position, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->actual_position, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->actual_position, 24u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->actual_torque, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->actual_torque, 8u, 0xffu);

    return (8);
}

int autonomous_temporary_maxon_position_tx_unpack(
    struct autonomous_temporary_maxon_position_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status_word = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->status_word |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->actual_position = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->actual_position |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->actual_position |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->actual_position |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    dst_p->actual_torque = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->actual_torque |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_maxon_position_tx_init(struct autonomous_temporary_maxon_position_tx_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_maxon_position_tx_t));

    return 0;
}

uint16_t autonomous_temporary_maxon_position_tx_status_word_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_maxon_position_tx_status_word_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_position_tx_status_word_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint32_t autonomous_temporary_maxon_position_tx_actual_position_encode(double value) {
    return (uint32_t)(value);
}

double autonomous_temporary_maxon_position_tx_actual_position_decode(uint32_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_position_tx_actual_position_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_maxon_position_tx_actual_torque_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_maxon_position_tx_actual_torque_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_position_tx_actual_torque_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

int autonomous_temporary_maxon_velocity_tx_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_maxon_velocity_tx_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->status_word, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->status_word, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->actual_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->actual_velocity, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->actual_velocity, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->actual_velocity, 24u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->pdw_duty_cicle_actual_value, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->pdw_duty_cicle_actual_value, 8u, 0xffu);

    return (8);
}

int autonomous_temporary_maxon_velocity_tx_unpack(
    struct autonomous_temporary_maxon_velocity_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status_word = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->status_word |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->actual_velocity = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->actual_velocity |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->actual_velocity |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->actual_velocity |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    dst_p->pdw_duty_cicle_actual_value = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->pdw_duty_cicle_actual_value |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_maxon_velocity_tx_init(struct autonomous_temporary_maxon_velocity_tx_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_maxon_velocity_tx_t));

    return 0;
}

uint16_t autonomous_temporary_maxon_velocity_tx_status_word_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_maxon_velocity_tx_status_word_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_velocity_tx_status_word_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint32_t autonomous_temporary_maxon_velocity_tx_actual_velocity_encode(double value) {
    return (uint32_t)(value);
}

double autonomous_temporary_maxon_velocity_tx_actual_velocity_decode(uint32_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_velocity_tx_actual_velocity_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

uint16_t autonomous_temporary_maxon_velocity_tx_pdw_duty_cicle_actual_value_encode(double value) {
    return (uint16_t)(value);
}

double autonomous_temporary_maxon_velocity_tx_pdw_duty_cicle_actual_value_decode(uint16_t value) {
    return ((double)value);
}

bool autonomous_temporary_maxon_velocity_tx_pdw_duty_cicle_actual_value_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}
