/**
 * @file data_dbc.c
 *
 * @brief This source file was generated by cantools version 40.2.3 Thu Jun 26 17:38:38 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "data_dbc.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int data_dbc_vcu__pack(
    uint8_t *dst_p,
    const struct data_dbc_vcu__t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->apps, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bps, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->trgt_power, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->trgt_power, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->trgt_power, 16u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(src_p->cnsm_power, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->cnsm_power, 8u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->cnsm_power, 16u, 0xffu);

    return (8);
}

int data_dbc_vcu__unpack(
    struct data_dbc_vcu__t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->apps = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bps = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->trgt_power = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->trgt_power |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->trgt_power |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->cnsm_power = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    dst_p->cnsm_power |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    dst_p->cnsm_power |= unpack_left_shift_u32(src_p[7], 16u, 0xffu);

    return (0);
}

int data_dbc_vcu__init(struct data_dbc_vcu__t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_vcu__t));

    return 0;
}

uint8_t data_dbc_vcu__apps_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu__apps_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu__apps_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t data_dbc_vcu__bps_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu__bps_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu__bps_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint32_t data_dbc_vcu__trgt_power_encode(double value)
{
    return (uint32_t)(value);
}

double data_dbc_vcu__trgt_power_decode(uint32_t value)
{
    return ((double)value);
}

bool data_dbc_vcu__trgt_power_is_in_range(uint32_t value)
{
    return (value <= 85000u);
}

uint32_t data_dbc_vcu__cnsm_power_encode(double value)
{
    return (uint32_t)(value);
}

double data_dbc_vcu__cnsm_power_decode(uint32_t value)
{
    return ((double)value);
}

bool data_dbc_vcu__cnsm_power_is_in_range(uint32_t value)
{
    return (value <= 85000u);
}

int data_dbc_vcu_1_pack(
    uint8_t *dst_p,
    const struct data_dbc_vcu_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->inv_temperature, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->inv_temperature, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->motor_temperature, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->motor_temperature, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->bms_voltage, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->bms_voltage, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->soc_hv, 0u, 0xffu);

    return (8);
}

int data_dbc_vcu_1_unpack(
    struct data_dbc_vcu_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->inv_temperature = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->inv_temperature |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->motor_temperature = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->motor_temperature |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->bms_voltage = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->bms_voltage |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->soc_hv = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int data_dbc_vcu_1_init(struct data_dbc_vcu_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_vcu_1_t));

    return 0;
}

uint16_t data_dbc_vcu_1_inv_temperature_encode(double value)
{
    return (uint16_t)(value - 40.0);
}

double data_dbc_vcu_1_inv_temperature_decode(uint16_t value)
{
    return ((double)value + 40.0);
}

bool data_dbc_vcu_1_inv_temperature_is_in_range(uint16_t value)
{
    return (value <= 260u);
}

uint16_t data_dbc_vcu_1_motor_temperature_encode(double value)
{
    return (uint16_t)(value - 40.0);
}

double data_dbc_vcu_1_motor_temperature_decode(uint16_t value)
{
    return ((double)value + 40.0);
}

bool data_dbc_vcu_1_motor_temperature_is_in_range(uint16_t value)
{
    return (value <= 60u);
}

uint16_t data_dbc_vcu_1_bms_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_vcu_1_bms_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_1_bms_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_vcu_1_soc_hv_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_1_soc_hv_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_1_soc_hv_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int data_dbc_vcu_2_pack(
    uint8_t *dst_p,
    const struct data_dbc_vcu_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->inv_faults, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->inv_faults, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->lmt1, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->lmt2, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->vcu_state, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->apps_error, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->power_plan, 0u, 0xffu);

    return (8);
}

int data_dbc_vcu_2_unpack(
    struct data_dbc_vcu_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->inv_faults = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->inv_faults |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->lmt1 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->lmt2 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->vcu_state = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->apps_error = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->power_plan = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int data_dbc_vcu_2_init(struct data_dbc_vcu_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_vcu_2_t));

    return 0;
}

uint16_t data_dbc_vcu_2_inv_faults_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_vcu_2_inv_faults_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_2_inv_faults_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint8_t data_dbc_vcu_2_lmt1_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_2_lmt1_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_2_lmt1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t data_dbc_vcu_2_lmt2_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_2_lmt2_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_2_lmt2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t data_dbc_vcu_2_vcu_state_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_2_vcu_state_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_2_vcu_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t data_dbc_vcu_2_apps_error_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_2_apps_error_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_2_apps_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t data_dbc_vcu_2_power_plan_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_2_power_plan_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_2_power_plan_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

int data_dbc_vcu_3_pack(
    uint8_t *dst_p,
    const struct data_dbc_vcu_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->inv_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->inv_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->ign, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->r2_d, 0u, 0xffu);

    return (8);
}

int data_dbc_vcu_3_unpack(
    struct data_dbc_vcu_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->inv_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->inv_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rpm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->ign = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->r2_d = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int data_dbc_vcu_3_init(struct data_dbc_vcu_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_vcu_3_t));

    return 0;
}

uint16_t data_dbc_vcu_3_inv_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_vcu_3_inv_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_3_inv_voltage_is_in_range(uint16_t value)
{
    return (value <= 620u);
}

uint16_t data_dbc_vcu_3_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_vcu_3_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_3_rpm_is_in_range(uint16_t value)
{
    return (value <= 7000u);
}

uint8_t data_dbc_vcu_3_ign_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_3_ign_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_3_ign_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t data_dbc_vcu_3_r2_d_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_3_r2_d_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_3_r2_d_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int data_dbc_vcu_4_pack(
    uint8_t *dst_p,
    const struct data_dbc_vcu_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->tcu_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->acu_state, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->alc_state, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->lv_soc, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->lv_soc, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->lv_voltage, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->lv_voltage, 8u, 0xffu);

    return (8);
}

int data_dbc_vcu_4_unpack(
    struct data_dbc_vcu_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->tcu_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->acu_state = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->alc_state = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->lv_soc = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->lv_soc |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->lv_voltage = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->lv_voltage |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

int data_dbc_vcu_4_init(struct data_dbc_vcu_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_vcu_4_t));

    return 0;
}

uint8_t data_dbc_vcu_4_tcu_state_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_4_tcu_state_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_4_tcu_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_vcu_4_acu_state_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_4_acu_state_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_4_acu_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_vcu_4_alc_state_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_vcu_4_alc_state_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_4_alc_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t data_dbc_vcu_4_lv_soc_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_vcu_4_lv_soc_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_4_lv_soc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t data_dbc_vcu_4_lv_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_vcu_4_lv_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_vcu_4_lv_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int data_dbc_imu__pack(
    uint8_t *dst_p,
    const struct data_dbc_imu__t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->accel_x_int, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->accel_x_int, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->accel_y_dec, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->accel_y_dec, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->accel_z_int, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->heatbit, 0u, 0xffu);

    return (8);
}

int data_dbc_imu__unpack(
    struct data_dbc_imu__t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->accel_x_int = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->accel_x_int |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_y_dec = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->accel_y_dec |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_z_int = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->heatbit = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int data_dbc_imu__init(struct data_dbc_imu__t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_imu__t));

    return 0;
}

uint16_t data_dbc_imu__accel_x_int_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_imu__accel_x_int_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_imu__accel_x_int_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t data_dbc_imu__accel_y_dec_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_imu__accel_y_dec_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_imu__accel_y_dec_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_imu__accel_z_int_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_imu__accel_z_int_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_imu__accel_z_int_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_imu__heatbit_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_imu__heatbit_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_imu__heatbit_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int data_dbc_imu_1_pack(
    uint8_t *dst_p,
    const struct data_dbc_imu_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->roll_int, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->roll_int, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pitch_dec, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pitch_dec, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->yaw_int, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->yaw_int, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->heartbit, 0u, 0xffu);

    return (8);
}

int data_dbc_imu_1_unpack(
    struct data_dbc_imu_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->roll_int = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->roll_int |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pitch_dec = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pitch_dec |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->yaw_int = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->yaw_int |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->heartbit = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int data_dbc_imu_1_init(struct data_dbc_imu_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_imu_1_t));

    return 0;
}

uint16_t data_dbc_imu_1_roll_int_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_imu_1_roll_int_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_imu_1_roll_int_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t data_dbc_imu_1_pitch_dec_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_imu_1_pitch_dec_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_imu_1_pitch_dec_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t data_dbc_imu_1_yaw_int_encode(double value)
{
    return (uint16_t)(value);
}

double data_dbc_imu_1_yaw_int_decode(uint16_t value)
{
    return ((double)value);
}

bool data_dbc_imu_1_yaw_int_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_imu_1_heartbit_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_imu_1_heartbit_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_imu_1_heartbit_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int data_dbc_dynamic_r_pack(
    uint8_t *dst_p,
    const struct data_dbc_dynamic_r_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->wheel_speed_rl, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->wheel_speed_rr, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->sus_pos_rl, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->sus_pos_rr, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->rr_pc, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->rl_pc, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->dy_st, 0u, 0xffu);

    return (8);
}

int data_dbc_dynamic_r_unpack(
    struct data_dbc_dynamic_r_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->wheel_speed_rl = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->wheel_speed_rr = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->sus_pos_rl = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->sus_pos_rr = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->rr_pc = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->rl_pc = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->dy_st = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int data_dbc_dynamic_r_init(struct data_dbc_dynamic_r_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_dynamic_r_t));

    return 0;
}

uint8_t data_dbc_dynamic_r_wheel_speed_rl_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_r_wheel_speed_rl_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_r_wheel_speed_rl_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_dynamic_r_wheel_speed_rr_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_r_wheel_speed_rr_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_r_wheel_speed_rr_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_dynamic_r_sus_pos_rl_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_r_sus_pos_rl_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_r_sus_pos_rl_is_in_range(uint8_t value)
{
    return (value <= 50u);
}

uint8_t data_dbc_dynamic_r_sus_pos_rr_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_r_sus_pos_rr_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_r_sus_pos_rr_is_in_range(uint8_t value)
{
    return (value <= 50u);
}

uint8_t data_dbc_dynamic_r_rr_pc_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_r_rr_pc_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_r_rr_pc_is_in_range(uint8_t value)
{
    return (value <= 30u);
}

uint8_t data_dbc_dynamic_r_rl_pc_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_r_rl_pc_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_r_rl_pc_is_in_range(uint8_t value)
{
    return (value <= 30u);
}

uint8_t data_dbc_dynamic_r_dy_st_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_r_dy_st_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_r_dy_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int data_dbc_dynamic_f_pack(
    uint8_t *dst_p,
    const struct data_dbc_dynamic_f_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->wheel_speed_fl, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->wheel_speed_fr, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->sus_pos_fl, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->sus_pos_fr, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->fr_pc, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->fl_pc, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->dy_st, 0u, 0xffu);

    return (8);
}

int data_dbc_dynamic_f_unpack(
    struct data_dbc_dynamic_f_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->wheel_speed_fl = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->wheel_speed_fr = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->sus_pos_fl = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->sus_pos_fr = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->fr_pc = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->fl_pc = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->dy_st = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int data_dbc_dynamic_f_init(struct data_dbc_dynamic_f_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_dynamic_f_t));

    return 0;
}

uint8_t data_dbc_dynamic_f_wheel_speed_fl_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_f_wheel_speed_fl_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_f_wheel_speed_fl_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_dynamic_f_wheel_speed_fr_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_f_wheel_speed_fr_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_f_wheel_speed_fr_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t data_dbc_dynamic_f_sus_pos_fl_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_f_sus_pos_fl_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_f_sus_pos_fl_is_in_range(uint8_t value)
{
    return (value <= 50u);
}

uint8_t data_dbc_dynamic_f_sus_pos_fr_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_f_sus_pos_fr_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_f_sus_pos_fr_is_in_range(uint8_t value)
{
    return (value <= 50u);
}

uint8_t data_dbc_dynamic_f_fr_pc_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_f_fr_pc_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_f_fr_pc_is_in_range(uint8_t value)
{
    return (value <= 30u);
}

uint8_t data_dbc_dynamic_f_fl_pc_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_f_fl_pc_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_f_fl_pc_is_in_range(uint8_t value)
{
    return (value <= 30u);
}

uint8_t data_dbc_dynamic_f_dy_st_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_dynamic_f_dy_st_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_dynamic_f_dy_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int data_dbc_data_logger_pack(
    uint8_t *dst_p,
    const struct data_dbc_data_logger_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->dl_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->recording_state, 0u, 0xffu);

    return (8);
}

int data_dbc_data_logger_unpack(
    struct data_dbc_data_logger_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->dl_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->recording_state = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int data_dbc_data_logger_init(struct data_dbc_data_logger_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct data_dbc_data_logger_t));

    return 0;
}

uint8_t data_dbc_data_logger_dl_state_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_data_logger_dl_state_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_data_logger_dl_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t data_dbc_data_logger_recording_state_encode(double value)
{
    return (uint8_t)(value);
}

double data_dbc_data_logger_recording_state_decode(uint8_t value)
{
    return ((double)value);
}

bool data_dbc_data_logger_recording_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
