/*
 * throttle_map_data.h - GENERATED by tools/throttle_map_editor.py
 * Edit with the tool (python tools/throttle_map_editor.py), then rebuild the firmware.
 *
 * throttle_map[speed][apps]: relative current, per mille of the inverter maximum
 *   > 0 = drive (SetRelCurrent), < 0 = regen (SetRelBrakeCurrent), 0 = coast
 * The VCU interpolates between points (throttle_map.c). Only included by throttle_map.c.
 */
#ifndef THROTTLE_MAP_DATA_H
#define THROTTLE_MAP_DATA_H

#include <stdint.h>

#define THROTTLE_MAP_APPS_POINTS  18
#define THROTTLE_MAP_SPEED_POINTS 13

// Accelerator axis (per mille of pedal travel)
static const uint16_t throttle_map_apps_axis[THROTTLE_MAP_APPS_POINTS] = {
    0, 30, 50, 80, 100, 120, 150, 180, 210, 250, 300, 400, 500, 600, 700, 800, 900, 1000
};

// Vehicle speed axis (km/h)
static const uint16_t throttle_map_speed_axis[THROTTLE_MAP_SPEED_POINTS] = {
    0, 6, 10, 15, 20, 30, 40, 50, 60, 70, 80, 90, 100
};

// Relative current (per mille), one row per speed, one column per accelerator point
static const int16_t throttle_map[THROTTLE_MAP_SPEED_POINTS][THROTTLE_MAP_APPS_POINTS] = {
    { -62,  -56,  -42,  -22,   -6,    8,   34,   68,   62,   62,   68,   85,  111,  119,  123,  133,  133,  150},  // 0 km/h
    {-188, -169, -127,  -68,  -18,    6,   22,   57,   46,   42,   53,   93,  146,  162,  165,  175,  175,  280},  // 6 km/h
    {-377, -339, -257, -143,  -42,    1,   15,   49,   41,   46,   85,  132,  180,  195,  203,  219,  224,  400},  // 10 km/h
    {-551, -497, -383, -226,  -81,  -10,    5,   40,   44,   71,  112,  163,  215,  256,  298,  349,  386,  550},  // 15 km/h
    {-689, -626, -492, -311, -136,  -34,    0,   30,   45,   82,  138,  204,  277,  324,  360,  364,  445,  650},  // 20 km/h
    {-782, -716, -576, -387, -204,  -78,    0,   10,   47,   90,  157,  243,  356,  476,  597,  716,  824, 1000},  // 30 km/h
    {-846, -781, -640, -450, -268, -133,    0,    0,   27,   82,  158,  258,  384,  507,  630,  752,  872, 1000},  // 40 km/h
    {-910, -851, -706, -505, -322, -188,  -67,    0,    6,   56,  134,  245,  371,  496,  622,  748,  874, 1000},  // 50 km/h
    {-968, -919, -769, -556, -373, -240, -126,   -8,    0,   35,  100,  228,  357,  485,  614,  742,  871, 1000},  // 60 km/h
    {-990, -990, -827, -582, -418, -280, -174,  -67,    0,   14,   80,  211,  342,  474,  605,  737,  868, 1000},  // 70 km/h
    {-990, -990, -842, -620, -471, -323, -213, -116,  -19,    0,   59,  193,  327,  462,  596,  731,  865, 1000},  // 80 km/h
    {-990, -990, -854, -650, -515, -378, -245, -157,  -68,    0,   37,  174,  312,  449,  587,  724,  862, 1000},  // 90 km/h
    {-990, -990, -865, -676, -551, -425, -273, -191, -109,    0,   14,  154,  295,  436,  577,  718,  859, 1000},  // 100 km/h
};

#endif  // THROTTLE_MAP_DATA_H
