/*
 * throttle_map_data.h - GENERATED by tools/throttle_map_editor.py
 * Edit with the tool (python tools/throttle_map_editor.py), then rebuild the firmware.
 *
 * throttle_map[speed][apps]: relative current, per mille of the inverter maximum
 *   > 0 = drive (SetRelCurrent), < 0 = regen (SetRelBrakeCurrent), 0 = coast
 * The VCU interpolates between points (throttle_map.c). Only included by throttle_map.c.
 */
#ifndef THROTTLE_MAP_DATA_H
#define THROTTLE_MAP_DATA_H

#include <stdint.h>

#define THROTTLE_MAP_APPS_POINTS  18
#define THROTTLE_MAP_SPEED_POINTS 13

// Accelerator axis (per mille of pedal travel)
static const uint16_t throttle_map_apps_axis[THROTTLE_MAP_APPS_POINTS] = {
    0, 30, 50, 80, 100, 120, 150, 180, 210, 250, 300, 400, 500, 600, 700, 800, 900, 1000
};

// Vehicle speed axis (km/h)
static const uint16_t throttle_map_speed_axis[THROTTLE_MAP_SPEED_POINTS] = {
    0, 6, 10, 15, 20, 30, 40, 50, 60, 70, 80, 90, 100
};

// Relative current (per mille), one row per speed, one column per accelerator point
static const int16_t throttle_map[THROTTLE_MAP_SPEED_POINTS][THROTTLE_MAP_APPS_POINTS] = {
    {   0,    0,    0,    0,    0,    0,   34,   68,  102,  147,  204,  318,  431,  471,  471,  471,  471,  471},  // 0 km/h
    {   0,    0,    0,    0,    0,    0,   22,   57,   91,  137,  195,  310,  425,  540,  655,  689,  689,  689},  // 6 km/h
    {-439, -439, -256,  -67,    0,    0,   15,   49,   84,  130,  188,  304,  420,  536,  652,  768,  884,  937},  // 10 km/h
    {-990, -990, -622, -200,  -40,    0,    5,   40,   76,  122,  181,  298,  415,  532,  649,  766,  883, 1000},  // 15 km/h
    {-990, -990, -661, -243, -100,    0,    0,   30,   66,  113,  172,  290,  408,  527,  645,  763,  881, 1000},  // 20 km/h
    {-990, -990, -716, -306, -184,  -65,    0,   10,   47,   95,  155,  276,  396,  517,  638,  758,  879, 1000},  // 30 km/h
    {-990, -990, -756, -406, -244, -142,    0,    0,   27,   76,  137,  261,  384,  507,  630,  753,  876, 1000},  // 40 km/h
    {-990, -990, -785, -479, -289, -200,  -67,    0,    6,   56,  119,  245,  371,  496,  622,  748,  874, 1000},  // 50 km/h
    {-990, -990, -809, -537, -355, -244, -126,   -8,    0,   35,  100,  228,  357,  485,  614,  742,  871, 1000},  // 60 km/h
    {-990, -990, -827, -582, -418, -280, -174,  -67,    0,   14,   80,  211,  342,  474,  605,  737,  868, 1000},  // 70 km/h
    {-990, -990, -842, -620, -471, -323, -213, -116,  -19,    0,   59,  193,  327,  462,  596,  731,  865, 1000},  // 80 km/h
    {-990, -990, -854, -650, -515, -378, -245, -157,  -68,    0,   37,  174,  312,  449,  587,  724,  862, 1000},  // 90 km/h
    {-990, -990, -865, -676, -551, -425, -273, -191, -109,    0,   14,  154,  295,  436,  577,  718,  859, 1000},  // 100 km/h
};

#endif  // THROTTLE_MAP_DATA_H
