"""
VCU throttle map and settings editor - table + 3D view, Fueltech / Haltech style.

Tabs:
  Mapa                    Core/Inc/throttle_map_data.h: relative-current map (accelerator x
                          vehicle speed). The whole file is rewritten on save.
  Conducao                Driving #defines (regen, ramps, PAU, speed calculation).
  Calibracao / Seguranca  APPS calibration, BSPD, R2D, inverter brake limits.
                          Locked until "Desbloquear" is ticked.

Settings are edited IN PLACE: only the number on each '#define NAME <number>' line is
replaced; comments and everything else stay as they are. If a define is not found on
exactly one plain line where it is expected, every setting from that file is locked
(shown, never written) - the file is not as the tool expects, so writing it is not safe.
Every value is range checked before saving, plus rule checks (APPS tolerance <= 10 % of
pedal travel). A file with an error is not written.

    python tools/throttle_map_editor.py             # open the editor
    python tools/throttle_map_editor.py --selftest  # check everything reads and writes back unchanged

Needs matplotlib (pip install matplotlib); tkinter comes with Python.
After saving: rebuild and flash the firmware.

Map units in the editor: accelerator and current in %, speed in km/h.
Map units in the file: per mille (0..1000 / -1000..1000), km/h.
Current > 0 = drive (SetRelCurrent), < 0 = regen (SetRelBrakeCurrent), 0 = coast.
"""

import contextlib
import re
import sys
import time
from collections import namedtuple
from itertools import pairwise
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from vcu_live import VcuLive

ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = ROOT / "Core" / "Inc" / "throttle_map_data.h"

TEMPLATE = """\
/*
 * throttle_map_data.h - GENERATED by tools/throttle_map_editor.py
 * Edit with the tool (python tools/throttle_map_editor.py), then rebuild the firmware.
 *
 * throttle_map[speed][apps]: relative current, per mille of the inverter maximum
 *   > 0 = drive (SetRelCurrent), < 0 = regen (SetRelBrakeCurrent), 0 = coast
 * The VCU interpolates between points (throttle_map.c). Only included by throttle_map.c.
 */
#ifndef THROTTLE_MAP_DATA_H
#define THROTTLE_MAP_DATA_H

#include <stdint.h>

#define THROTTLE_MAP_APPS_POINTS  {na}
#define THROTTLE_MAP_SPEED_POINTS {ns}

// Accelerator axis (per mille of pedal travel)
static const uint16_t throttle_map_apps_axis[THROTTLE_MAP_APPS_POINTS] = {{
    {apps}
}};

// Vehicle speed axis (km/h)
static const uint16_t throttle_map_speed_axis[THROTTLE_MAP_SPEED_POINTS] = {{
    {speed}
}};

// Relative current (per mille), one row per speed, one column per accelerator point
static const int16_t throttle_map[THROTTLE_MAP_SPEED_POINTS][THROTTLE_MAP_APPS_POINTS] = {{
{rows}
}};

#endif  // THROTTLE_MAP_DATA_H
"""


# ============================ MAP FILE FORMAT ============================


def read_data(path=DATA_FILE):
    """Return (apps_axis, speed_axis, table[speed][apps]) from the .h file."""
    text = re.sub(r"/\*.*?\*/|//[^\n]*", "", path.read_text(), flags=re.DOTALL)
    arrays = {
        name: [int(n) for n in re.findall(r"-?\d+", body)]
        for name, body in re.findall(
            r"(\w+)\s*\[[^=]*=\s*\{(.*?)\};", text, flags=re.DOTALL
        )
    }
    apps, speed = arrays["throttle_map_apps_axis"], arrays["throttle_map_speed_axis"]
    flat = arrays["throttle_map"]
    if len(flat) != len(apps) * len(speed):
        raise ValueError(f"{path.name}: array sizes do not match the axes")
    table = [flat[i * len(apps) : (i + 1) * len(apps)] for i in range(len(speed))]
    return apps, speed, table


def validate(apps, speed, table):
    """Return a list of problems with the map (empty = OK to write)."""
    errors = []
    if len(apps) < 2 or len(speed) < 2:
        errors.append("Each axis needs at least 2 points")
    if any(b <= a for a, b in pairwise(apps)) or apps[0] < 0 or apps[-1] > 1000:
        errors.append("Accelerator axis must increase strictly, 0..100 %")
    if any(b <= a for a, b in pairwise(speed)) or speed[0] < 0:
        errors.append("Speed axis must increase strictly, from 0 km/h")
    if any(not -1000 <= v <= 1000 for row in table for v in row):
        errors.append("Current must be between -100 % and 100 %")
    return errors


def write_data(apps, speed, table, path=DATA_FILE):
    width = max(len(str(v)) for row in table for v in row)
    rows = "\n".join(
        "    {" + ", ".join(f"{v:{width}d}" for v in row) + f"}},  // {s} km/h"
        for s, row in zip(speed, table)
    )
    join = lambda values: ", ".join(str(v) for v in values)
    path.write_text(
        TEMPLATE.format(
            na=len(apps), ns=len(speed), apps=join(apps), speed=join(speed), rows=rows
        )
    )


# =============================== SETTINGS ===============================

DRIVING, SAFETY = "Conducao", "Calibracao / Seguranca"
TC, PAU, APPS_H, APPS_C, BSPD, CANU = (
    "Core/Inc/throttle_control.h",
    "Core/Inc/pau_control.h",
    "Core/Inc/APPS.h",
    "Core/Src/APPS.c",
    "Core/Inc/bspd.h",
    "Core/Inc/CAN_utils.h",
)

Setting = namedtuple("Setting", "tab file name kind lo hi label")
SETTINGS = [
    Setting(DRIVING, TC, "THROTTLE_REGEN_ENABLE", "bool", 0, 1, "Regen ligada"),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_TORQUE_RISE_MAX_PCT_S",
        "int",
        0,
        10000,
        "Subida max. do binario (%/s, 0 = sem limite) - picos de corrente",
    ),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_REGEN_RAMP_UP_MS",
        "int",
        1,
        5000,
        "Regen: subida 0 -> 100 % (ms)",
    ),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_REGEN_RAMP_DOWN_MS",
        "int",
        1,
        5000,
        "Regen: descida 100 -> 0 % (ms)",
    ),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_REGEN_FADE_START_V",
        "int",
        0,
        1000,
        "Regen: reduz acima de (V, 0 = off)",
    ),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_REGEN_CUTOFF_V",
        "int",
        0,
        1000,
        "Regen: corta a partir de (V, 0 = off)",
    ),
    Setting(
        DRIVING, TC, "THROTTLE_GEAR_RATIO", "float", 1, 50, "Relacao de transmissao"
    ),
    Setting(
        DRIVING, TC, "THROTTLE_WHEEL_RADIUS_M", "float", 0.1, 0.5, "Raio do pneu (m)"
    ),
    Setting(
        DRIVING,
        CANU,
        "MOTOR_POLE_PAIRS",
        "int",
        1,
        20,
        "Pares de polos do motor (ERPM / pares = rpm)",
    ),
    Setting(
        DRIVING,
        PAU,
        "PAU_CONTROL_ENABLE",
        "bool",
        0,
        1,
        "PAU (limite de potencia) ligado",
    ),
    Setting(
        DRIVING,
        PAU,
        "PAU_POWER_LIMIT_THRESHOLD_W",
        "int",
        0,
        200000,
        "PAU: comeca a limitar acima de (W)",
    ),
    Setting(
        DRIVING, PAU, "PAU_MAX_POWER_W", "int", 1, 200000, "PAU: potencia maxima (W)"
    ),
    Setting(
        DRIVING,
        PAU,
        "PAU_MAX_THROTTLE_AT_80KW_PERCENT",
        "int",
        0,
        100,
        "PAU: tracao permitida na potencia maxima (%)",
    ),
    Setting(SAFETY, APPS_H, "APPS_MIN_BITS", "int", 0, 4095, "APPS1 a 0 % (bits)"),
    Setting(SAFETY, APPS_H, "APPS_MAX_BITS", "int", 0, 4095, "APPS1 a 100 % (bits)"),
    Setting(
        SAFETY,
        APPS_H,
        "APPS_TOLERANCE",
        "int",
        1,
        4095,
        "Discordancia max. APPS1/APPS2 (bits, <= 10 % do curso)",
    ),
    Setting(
        SAFETY,
        APPS_H,
        "APPS_HYSTERESIS_BITS",
        "int",
        0,
        20,
        "Histerese do pedal (bits)",
    ),
    Setting(
        SAFETY, APPS_H, "APPS2_OFFSET", "int", 0, 4095, "APPS2 -> APPS1: offset (bits)"
    ),
    Setting(
        SAFETY,
        APPS_H,
        "APPS2_GAIN_X1000",
        "int",
        500,
        4000,
        "APPS2 -> APPS1: ganho x1000",
    ),
    Setting(
        SAFETY,
        APPS_H,
        "APPS_MA_WINDOW_SIZE",
        "int",
        1,
        20,
        "Media movel do APPS (amostras)",
    ),
    Setting(
        SAFETY,
        APPS_H,
        "MAX_APPS_TIMEOUT_MS",
        "int",
        10,
        500,
        "Sem frame APPS -> acelerador 0 (ms)",
    ),
    Setting(
        SAFETY,
        APPS_C,
        "APPS_TIMEOUT_MS",
        "int",
        1,
        1000,
        "Erro APPS persistente -> corte (ms)",
    ),
    Setting(
        SAFETY,
        BSPD,
        "BSPD_BRAKE_THRESHOLD",
        "float",
        1,
        200,
        "BSPD: travagem forte a partir de (bar)",
    ),
    Setting(
        SAFETY,
        BSPD,
        "BSPD_ACCEL_THRESHOLD",
        "int",
        0,
        1000,
        "BSPD: acelerador pressionado a partir de (0-1000)",
    ),
    Setting(
        SAFETY,
        BSPD,
        "BSPD_ACTIVATION_DELAY",
        "int",
        1,
        500,
        "BSPD: atraso a ativar (ms)",
    ),
    Setting(
        SAFETY,
        BSPD,
        "BSPD_DEACTIVATION_DELAY",
        "int",
        0,
        1000,
        "BSPD: atraso a desativar (ms)",
    ),
    Setting(
        SAFETY,
        CANU,
        "BRAKE_PRESSURE_THRESHOLD",
        "int",
        1,
        100,
        "R2D: pressao de travao minima (bar)",
    ),
    Setting(
        SAFETY,
        TC,
        "THROTTLE_SEND_BRAKE_LIMITS",
        "bool",
        0,
        1,
        "VCU envia limites de travagem aos inversores",
    ),
    Setting(
        SAFETY,
        TC,
        "THROTTLE_MAX_AC_BRAKE_CURRENT_A",
        "int",
        0,
        850,
        "Limite de travagem AC por inversor (A)",
    ),
    Setting(
        SAFETY,
        TC,
        "THROTTLE_MAX_DC_BRAKE_CURRENT_A",
        "int",
        0,
        850,
        "Limite de travagem DC por inversor (A)",
    ),
]
BY_NAME = {s.name: s for s in SETTINGS}

# '#define NAME <number>[U|f]' followed only by spaces and an optional // comment
DEFINE_RE = r"^([ \t]*#define[ \t]+{name}[ \t]+)(-?\d+(?:\.\d+)?)([uUfF]?)(?=[ \t]*(?://[^\r\n]*)?\r?$)"


def read_file(rel):
    with open(
        ROOT / rel, encoding="utf-8", newline=""
    ) as f:  # newline="" keeps CRLF as is
        return f.read()


def find_define(text, name):
    """The match for '#define NAME <number>' if it is on exactly one plain line, else None."""
    matches = list(
        re.finditer(DEFINE_RE.format(name=re.escape(name)), text, flags=re.MULTILINE)
    )
    return matches[0] if len(matches) == 1 else None


def parse_value(setting, literal):
    """Number from the file, or None if it does not fit the setting's type."""
    try:
        value = float(literal) if setting.kind == "float" else int(literal)
    except ValueError:
        return None
    if setting.kind == "bool" and value not in (0, 1):
        return None
    return value


def read_settings():
    """{name: value}, with None for LOCKED settings. If any expected define of a file is
    missing, duplicated or not a plain number, all settings of that file are locked."""
    values = {}
    for rel in {s.file for s in SETTINGS}:
        names = [s.name for s in SETTINGS if s.file == rel]
        try:
            text = read_file(rel)
        except OSError:
            text = ""
        found = {}
        for name in names:
            match = find_define(text, name)
            found[name] = parse_value(BY_NAME[name], match.group(2)) if match else None
        file_ok = all(v is not None for v in found.values())
        values.update({name: (found[name] if file_ok else None) for name in names})
    return values


def check_settings(values):
    """[(file, message)] for out-of-range values and rule checks. None values are skipped."""
    errors = []
    for s in SETTINGS:
        v = values.get(s.name)
        if v is not None and not s.lo <= v <= s.hi:
            errors.append((s.file, f"{s.name} = {v:g} fora de {s.lo:g}..{s.hi:g}"))
    get = values.get
    lo, hi, tol = get("APPS_MIN_BITS"), get("APPS_MAX_BITS"), get("APPS_TOLERANCE")
    if None not in (lo, hi, tol):
        if hi <= lo:
            errors.append((APPS_H, "APPS_MIN_BITS tem de ser menor que APPS_MAX_BITS"))
        elif tol > (hi - lo) / 10:
            errors.append(
                (
                    APPS_H,
                    f"APPS_TOLERANCE > 10 % do curso do pedal ({(hi - lo) / 10:.0f} bits) - regra",
                )
            )
    fade, cutoff = get("THROTTLE_REGEN_FADE_START_V"), get("THROTTLE_REGEN_CUTOFF_V")
    if None not in (fade, cutoff) and cutoff > 0 and fade >= cutoff:
        errors.append(
            (
                TC,
                "THROTTLE_REGEN_FADE_START_V tem de ser menor que THROTTLE_REGEN_CUTOFF_V",
            )
        )
    pau_lo, pau_hi = get("PAU_POWER_LIMIT_THRESHOLD_W"), get("PAU_MAX_POWER_W")
    if None not in (pau_lo, pau_hi) and pau_lo >= pau_hi:
        errors.append(
            (PAU, "PAU_POWER_LIMIT_THRESHOLD_W tem de ser menor que PAU_MAX_POWER_W")
        )
    return errors


def format_value(setting, value):
    if setting.kind != "float":
        return str(int(value))
    text = f"{value:.6g}"
    return text if ("." in text or "e" in text) else text + ".0"


def write_settings(new_values):
    """Write changed values, file by file. Returns (written_files, error_messages).
    A file is skipped if any of its values fails the checks, or if a define line no
    longer matches exactly once (file changed since it was read)."""
    errors = check_settings(new_values)
    blocked = {f for f, _ in errors}
    messages = [m for _, m in errors]
    written = []
    for rel in sorted({BY_NAME[n].file for n in new_values}):
        if rel in blocked:
            continue
        text = read_file(rel)
        new_text = text
        for name, value in new_values.items():
            s = BY_NAME[name]
            if s.file != rel or value is None:
                continue
            match = find_define(new_text, name)
            if match is None:
                messages.append(
                    f"{name}: linha do #define nao encontrada em {rel} - ficheiro nao gravado"
                )
                new_text = None
                break
            if parse_value(s, match.group(2)) == value:
                continue
            literal = format_value(s, value)
            new_text = new_text[: match.start(2)] + literal + new_text[match.end(2) :]
        if new_text is not None and new_text != text:
            with open(ROOT / rel, "w", encoding="utf-8", newline="") as f:
                f.write(new_text)
            written.append(rel)
    return written, messages


def selftest():
    data = read_data()
    assert not validate(*data), validate(*data)
    tmp = DATA_FILE.with_suffix(".selftest.h")
    try:
        write_data(*data, path=tmp)
        assert read_data(tmp) == data, "map file does not read back the same"
    finally:
        tmp.unlink(missing_ok=True)

    values = read_settings()
    locked = [n for n, v in values.items() if v is None]
    assert not locked, f"locked (define line not found): {locked}"
    # Writing the same values must not touch any file
    written, _ = write_settings(dict(values))
    assert not written, f"unchanged values rewrote {written}"
    # A define that is missing or duplicated must lock
    assert find_define("#define X 1\n", "APPS_MIN_BITS") is None
    assert (
        find_define(
            "#define APPS_MIN_BITS 1\n#define APPS_MIN_BITS 2\n", "APPS_MIN_BITS"
        )
        is None
    )
    assert find_define("#define APPS_MIN_BITS (1 + 2)\n", "APPS_MIN_BITS") is None
    match = find_define("#define APPS_MIN_BITS 1118U  // c\r\n", "APPS_MIN_BITS")
    assert match is not None and match.group(2) == "1118"
    problems = check_settings(values)
    print(
        f"OK - map {len(data[1])}x{len(data[0])}, {len(values)} settings found, none locked"
    )
    for _, msg in problems:
        print(f"  current value needs attention: {msg}")


# ================================== GUI ==================================

DEFAULT_VIEW = (
    18,
    -145,
)  # 3D view (elevation, azimuth): speed along the front, accelerator to the side


def cell_color(percent):
    """White at 0, red for drive, blue for regen, stronger with the value."""
    shade = int(255 * (1 - 0.65 * min(abs(percent) / 100, 1)))
    if percent > 0:
        return f"#ff{shade:02x}{shade:02x}"
    if percent < 0:
        return f"#{shade:02x}{shade:02x}ff"
    return "#ffffff"


def run_gui():
    import tkinter as tk
    from tkinter import messagebox, ttk
    from typing import cast

    import numpy as np
    from matplotlib.artist import Artist
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
    from matplotlib.figure import Figure
    from mpl_toolkits.mplot3d import Axes3D

    root = tk.Tk()
    root.title("VCU - mapa do acelerador e configuracao")

    bar = tk.Frame(root)
    bar.pack(fill="x", padx=4, pady=4)
    tabs = ttk.Notebook(root)
    tabs.pack(fill="both", expand=True)
    map_tab = tk.Frame(tabs)
    tabs.add(map_tab, text="Mapa")
    setting_tabs = {
        DRIVING: tk.Frame(tabs, padx=8, pady=8),
        SAFETY: tk.Frame(tabs, padx=8, pady=8),
    }
    for name, frame in setting_tabs.items():
        tabs.add(frame, text=name)

    # ------------------------------- Map tab -------------------------------
    table_frame = tk.Frame(map_tab)
    table_frame.pack(padx=4, pady=4)

    fig = Figure(figsize=(11, 5.5))
    ax3d = cast(Axes3D, fig.add_subplot(1, 1, 1, projection="3d"))
    ax3d.view_init(*DEFAULT_VIEW)
    bottom = tk.Frame(map_tab)
    bottom.pack(fill="both", expand=True)
    live_frame = tk.LabelFrame(bottom, text="VCU ao vivo (ST-LINK)", padx=6, pady=4)
    live_frame.pack(side="right", fill="y", padx=4, pady=4)
    tk.Label(live_frame, text="Carrega em 'Ligar VCU'\n(CubeIDE fora de debug)", fg="gray").pack()
    canvas = FigureCanvasTkAgg(fig, master=bottom)
    canvas.get_tk_widget().pack(side="left", fill="both", expand=True)

    entries = {}  # (row, col) -> Entry; row 0 = accelerator axis, col 0 = speed axis
    grid_size = {"rows": range(0), "cols": range(0)}
    # Table cell shown as a yellow dot in the 3D view, and where a mouse click started
    selected_cell: tuple[int, int] | None = None
    marker: Artist | None = None
    press_start: tuple[float, float] | None = None
    # Live link to the VCU (tools/vcu_live.py): green dot + highlighted cell = operating point
    live: VcuLive | None = None
    live_marker: Artist | None = None
    live_cell: tuple[int, int] | None = None
    live_cell_default_hl = 0
    live_labels: dict[str, tk.Label] = {}

    def collect_map():
        """Read the grid back into file units. Raises ValueError on a bad number."""
        rows, cols = grid_size["rows"], grid_size["cols"]
        apps = [round(float(entries[0, c].get()) * 10) for c in cols]
        speed = [round(float(entries[r, 0].get())) for r in rows]
        table = [[round(float(entries[r, c].get()) * 10) for c in cols] for r in rows]
        return apps, speed, table

    def refresh_map(_event=None):
        nonlocal marker, live_marker
        try:
            apps, speed, table = collect_map()
        except ValueError:
            status.config(text="Valor invalido numa celula do mapa", fg="red")
            return
        for r in grid_size["rows"]:
            for c in grid_size["cols"]:
                entries[r, c].config(bg=cell_color(table[r - 1][c - 1] / 10))
        elev, azim = ax3d.elev, ax3d.azim
        ax3d.clear()
        ax3d.computed_zorder = (
            False  # draw by zorder, so the selection dot stays on top of the surface
        )
        x, y = np.meshgrid([a / 10 for a in apps], speed)
        ax3d.plot_surface(
            x,
            y,
            np.array(table) / 10,
            cmap="coolwarm",
            vmin=-100,
            vmax=100,
            edgecolor="k",
            linewidth=0.3,
        )
        ax3d.set_xlabel("Acelerador (%)")
        ax3d.set_ylabel("Velocidade (km/h)")
        ax3d.set_zlabel("Corrente (%)")
        ax3d.set_zlim(-100, 100)
        ax3d.view_init(elev, azim)
        marker = None  # cleared with the axes
        live_marker = None  # redrawn by the next live poll
        draw_marker(apps, speed, table)
        fig.tight_layout()
        canvas.draw_idle()

    # --- Link between the 3D view and the table ---
    def draw_marker(apps, speed, table):
        nonlocal marker
        if marker is not None:
            marker.remove()
            marker = None
        cell = selected_cell
        if cell is None:
            return
        r, c = cell
        value = table[r - 1][c - 1] / 10
        (marker,) = ax3d.plot(
            [apps[c - 1] / 10],
            [speed[r - 1]],
            [value],
            linestyle="none",
            marker="o",
            markersize=10,
            markerfacecolor="yellow",
            markeredgecolor="black",
            markeredgewidth=1.5,
            zorder=10,
        )
        status.config(
            text=f"Celula: {speed[r - 1]} km/h, acelerador {apps[c - 1] / 10:g} % -> {value:g} %",
            fg="black",
        )

    def show_selection(row, col):
        """A table cell got the focus: mark it in the 3D view."""
        nonlocal selected_cell
        selected_cell = (row, col)
        try:
            draw_marker(*collect_map())
        except ValueError:
            return
        canvas.draw_idle()

    def on_press(event):
        nonlocal press_start
        press_start = (event.x, event.y) if event.inaxes is ax3d else None

    def on_release(event):
        """Click (not a rotation drag) on the 3D view: select the nearest point in the table."""
        start = press_start
        if (
            start is None
            or event.inaxes is not ax3d
            or abs(event.x - start[0]) > 3
            or abs(event.y - start[1]) > 3
        ):
            return
        try:
            apps, speed, table = collect_map()
        except ValueError:
            return
        # Project every grid point to screen pixels and take the closest one
        cells = [(r, c) for r in grid_size["rows"] for c in grid_size["cols"]]
        points = np.array(
            [
                [apps[c - 1] / 10, speed[r - 1], table[r - 1][c - 1] / 10, 1.0]
                for r, c in cells
            ]
        )
        projected = points @ ax3d.get_proj().T
        screen = ax3d.transData.transform(projected[:, :2] / projected[:, 3:4])
        distances = np.hypot(screen[:, 0] - event.x, screen[:, 1] - event.y)
        nearest = int(np.argmin(distances))
        if distances[nearest] <= 25:  # pixels
            move(*cells[nearest])

    canvas.mpl_connect("button_press_event", on_press)
    canvas.mpl_connect("button_release_event", on_release)

    def move(row, col):
        if (row, col) in entries:
            entries[row, col].focus_set()
            entries[row, col].select_range(0, "end")

    def add_cell(row, col, value, axis=False):
        # Grid is shifted by one row/column to make room for the axis titles
        e = tk.Entry(
            table_frame,
            width=6,
            justify="right",
            bg="#e4e4e4" if axis else "white",
            font=("Consolas", 9, "bold" if axis else "normal"),
        )
        e.insert(0, value)
        e.grid(row=row + 1, column=col + 1)
        e.bind("<Return>", refresh_map)
        e.bind("<FocusOut>", refresh_map)
        e.bind("<Up>", lambda _e: move(row - 1, col))
        e.bind("<Down>", lambda _e: move(row + 1, col))
        if not axis:
            e.bind("<FocusIn>", lambda _e: show_selection(row, col))
        entries[row, col] = e

    def load_map():
        apps, speed, table = read_data()
        for widget in table_frame.winfo_children():
            widget.destroy()
        entries.clear()
        grid_size["rows"] = range(1, len(speed) + 1)
        grid_size["cols"] = range(1, len(apps) + 1)
        title = ("Arial", 10, "bold")
        tk.Label(table_frame, text="ACELERADOR (%)", font=title).grid(
            row=0, column=2, columnspan=len(apps), sticky="w"
        )
        tk.Label(table_frame, text="\n".join("VELOCIDADE") + "\n\nkm", font=title).grid(
            row=2, column=0, rowspan=len(speed), padx=(0, 4)
        )
        tk.Label(table_frame, text="km/h \\ %").grid(row=1, column=1)
        for c, a in zip(grid_size["cols"], apps):
            add_cell(0, c, f"{a / 10:g}", axis=True)
        for r, s, row in zip(grid_size["rows"], speed, table):
            add_cell(r, 0, str(s), axis=True)
            for c, v in zip(grid_size["cols"], row):
                add_cell(r, c, f"{v / 10:g}")
        refresh_map()

    # ---------------------------- Settings tabs ----------------------------
    fields = {}  # name -> (var, widget, note_label)
    loaded = {}  # name -> value read from the file (None = locked)
    unlock = tk.IntVar(value=0)

    def field_value(name):
        var = fields[name][0]
        return float(var.get()) if BY_NAME[name].kind == "float" else int(var.get())

    def apply_states():
        for name, (var, widget, note) in fields.items():
            s = BY_NAME[name]
            editable = loaded.get(name) is not None and (
                s.tab == DRIVING or unlock.get()
            )
            widget.config(state="normal" if editable else "disabled")

    def mark_settings(_event=None):
        """Red note on out-of-range / rule problems, grey note otherwise."""
        values = {}
        for name in fields:
            if loaded.get(name) is None:
                continue
            try:
                values[name] = field_value(name)
            except ValueError:
                fields[name][2].config(text="numero invalido", fg="red")
        problems = {}
        for rel, msg in check_settings(values):
            for name in re.findall(r"[A-Z][A-Z0-9_]{3,}", msg):
                problems.setdefault(name, msg)
        for name, (var, widget, note) in fields.items():
            if loaded.get(name) is None:
                note.config(text="#define nao encontrado - BLOQUEADO", fg="red")
            elif name in values:
                s = BY_NAME[name]
                msg = problems.get(name)
                note.config(
                    text=msg if msg else f"{s.lo:g}..{s.hi:g}",
                    fg="red" if msg else "gray",
                )

    tk.Checkbutton(
        setting_tabs[SAFETY],
        text="Desbloquear edicao (valores de seguranca)",
        variable=unlock,
        command=apply_states,
        fg="red",
    ).grid(row=0, column=0, columnspan=4, sticky="w", pady=(0, 8))
    row_of = {DRIVING: 0, SAFETY: 1}
    for s in SETTINGS:
        frame = setting_tabs[s.tab]
        r = row_of[s.tab]
        row_of[s.tab] += 1
        tk.Label(frame, text=s.label, anchor="w").grid(
            row=r, column=0, sticky="w", padx=(0, 8)
        )
        var = tk.IntVar() if s.kind == "bool" else tk.StringVar()
        if s.kind == "bool":
            widget = tk.Checkbutton(frame, variable=var, command=mark_settings)
        else:
            widget = tk.Entry(frame, textvariable=var, width=12, justify="right")
            widget.bind("<Return>", mark_settings)
            widget.bind("<FocusOut>", mark_settings)
        widget.grid(row=r, column=1, sticky="w")
        tk.Label(frame, text=f"{s.name}  ({Path(s.file).name})", fg="gray").grid(
            row=r, column=2, sticky="w", padx=8
        )
        note = tk.Label(frame, anchor="w")
        note.grid(row=r, column=3, sticky="w")
        fields[s.name] = (var, widget, note)

    def load_settings():
        loaded.clear()
        loaded.update(read_settings())
        for name, (var, widget, note) in fields.items():
            value = loaded[name]
            if BY_NAME[name].kind == "bool":
                var.set(value or 0)
            else:
                var.set("" if value is None else f"{value:g}")
        apply_states()
        mark_settings()

    # ------------------------------- Buttons -------------------------------
    def load_all():
        try:
            load_map()
        except (OSError, KeyError, ValueError) as err:
            messagebox.showerror("Erro ao ler o mapa", str(err))
        load_settings()
        status.config(text="Lido", fg="black")

    def save_all():
        problems: list[str] = []
        written: list[str] = []
        # Map
        try:
            data = collect_map()
        except ValueError:
            data = None
            problems.append("Mapa: ha uma celula que nao e numero")
        if data is not None:
            map_errors = validate(*data)
            try:
                unchanged = data == read_data()
            except (OSError, KeyError, ValueError):
                unchanged = (
                    False  # Unreadable file: rewrite it from the (valid) editor values
                )
            if map_errors:
                problems += [f"Mapa: {e}" for e in map_errors]
            elif not unchanged:
                write_data(*data)
                written.append(str(DATA_FILE.relative_to(ROOT)))
        # Settings: only editable ones (found in the file, and safety only when unlocked)
        new_values = {}
        for name in fields:
            s = BY_NAME[name]
            if loaded.get(name) is None or (s.tab == SAFETY and not unlock.get()):
                continue
            try:
                new_values[name] = field_value(name)
            except ValueError:
                problems.append(f"{name}: numero invalido")
        if not any(p.endswith("numero invalido") for p in problems):
            files, msgs = write_settings(new_values)
            written += files
            problems += msgs
        load_settings()
        mark_settings()
        if problems:
            messagebox.showwarning("Nao foi tudo gravado", "\n".join(problems))
        status.config(
            text=(
                f"Gravado {time.strftime('%H:%M:%S')}: {', '.join(written)} - compila e grava o firmware"
                if written
                else "Nada alterado para gravar"
            ),
            fg="green" if written and not problems else "black",
        )

    tk.Button(bar, text="Gravar", width=10, command=save_all).pack(side="left")
    tk.Button(bar, text="Recarregar", width=10, command=load_all).pack(
        side="left", padx=4
    )

    def reset_view():
        ax3d.view_init(*DEFAULT_VIEW)
        canvas.draw_idle()

    tk.Button(bar, text="Vista 3D default", command=reset_view).pack(side="left")

    # ------------------------- Live link to the VCU -------------------------
    def set_live_cell(cell):
        """Green border on the table cell closest to the live operating point."""
        nonlocal live_cell, live_cell_default_hl
        if cell == live_cell:
            return
        if live_cell in entries:
            entries[live_cell].config(highlightthickness=live_cell_default_hl)
        live_cell = cell
        if cell in entries:
            live_cell_default_hl = int(entries[cell].cget("highlightthickness"))
            entries[cell].config(highlightthickness=3, highlightbackground="#00b000", highlightcolor="#00b000")

    def draw_live(values):
        """Green dot at the live pedal / speed / map value, and the nearest table cell."""
        nonlocal live_marker
        if live_marker is not None:
            live_marker.remove()
            live_marker = None
        pedal = values.get("throttle.pedal_1000")
        speed_now = values.get("throttle.speed_kmh")
        map_now = values.get("throttle.map_1000")
        if pedal is None or speed_now is None or map_now is None:
            return
        (live_marker,) = ax3d.plot([pedal / 10], [speed_now], [map_now / 10], linestyle="none", marker="o",
                                   markersize=11, markerfacecolor="#00d000", markeredgecolor="black",
                                   markeredgewidth=1.5, zorder=11)
        try:
            apps, speed, _ = collect_map()
        except ValueError:
            return
        col = min(range(len(apps)), key=lambda i: abs(apps[i] - pedal)) + 1
        row = min(range(len(speed)), key=lambda i: abs(speed[i] - speed_now)) + 1
        set_live_cell((row, col))
        canvas.draw_idle()

    def poll_live():
        link = live
        if link is None:
            return
        try:
            values = link.read()
        except Exception as err:  # noqa: BLE001 - probe unplugged, USB/pyocd error: message, not a crash
            disconnect_live(f"Ligacao a VCU perdida: {err}")
            return
        for v in link.variables:
            live_labels[v.expr].config(text=v.text(values[v.expr]))
        draw_live(values)
        root.after(200, poll_live)

    def disconnect_live(message):
        nonlocal live, live_marker
        link = live
        live = None
        if link is not None:
            with contextlib.suppress(Exception):  # probe may already be gone
                link.close()
        if live_marker is not None:
            live_marker.remove()
            live_marker = None
            canvas.draw_idle()
        set_live_cell(None)
        live_button.config(text="Ligar VCU")
        status.config(text=message, fg="black")

    def toggle_live():
        nonlocal live
        if live is not None:
            disconnect_live("Desligado da VCU")
            return
        try:
            sys.path.insert(0, str(Path(__file__).resolve().parent))
            from vcu_live import VcuLive

            link = VcuLive()
            link.connect()
        except Exception as err:  # noqa: BLE001 - any connect problem becomes a message
            messagebox.showerror("VCU ao vivo", str(err))
            return
        live = link
        for widget in live_frame.winfo_children():
            widget.destroy()
        live_labels.clear()
        for i, v in enumerate(link.variables):
            tk.Label(live_frame, text=v.label, anchor="w").grid(row=i, column=0, sticky="w")
            live_labels[v.expr] = tk.Label(live_frame, text="-", width=24, anchor="e", font=("Consolas", 10, "bold"))
            live_labels[v.expr].grid(row=i, column=1, sticky="e")
        for j, expr in enumerate(link.missing):
            tk.Label(live_frame, text=f"{expr}: nao existe no ELF", fg="gray").grid(
                row=len(link.variables) + j, column=0, columnspan=2, sticky="w")
        live_button.config(text="Desligar VCU")
        status.config(text="Ligado a VCU (ST-LINK) - so leitura", fg="green")
        poll_live()

    live_button = tk.Button(bar, text="Ligar VCU", width=12, command=toggle_live)
    live_button.pack(side="left", padx=4)

    def on_close():
        disconnect_live("")
        root.destroy()

    root.protocol("WM_DELETE_WINDOW", on_close)
    tk.Label(bar, text="Mapa: + tracao (vermelho), - regen (azul)").pack(
        side="left", padx=8
    )
    status = tk.Label(bar, anchor="e")
    status.pack(side="right")

    load_all()
    root.mainloop()


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        selftest()
    else:
        run_gui()
