"""
VCU throttle map and settings editor - table + 3D view, Fueltech / Haltech style.

Tabs:
  Mapa                    Core/Inc/throttle_map_data.h: relative-current map (accelerator x
                          vehicle speed). The whole file is rewritten on save.
  Conducao                Driving #defines (regen, ramps, PAU, speed calculation).
  Tracao / Vetorizacao    Traction control (PI) and torque vectoring (traction_control_torque_vectoring.h).
  Calibracao / Seguranca  APPS calibration, BSPD, R2D, inverter brake limits.
                          Locked until "Desbloquear" is ticked.

Settings are edited IN PLACE: only the number on each '#define NAME <number>' line is
replaced; comments and everything else stay as they are. If a define is not found on
exactly one plain line where it is expected, every setting from that file is locked
(shown, never written) - the file is not as the tool expects, so writing it is not safe.
Every value is range checked, plus rule checks (APPS tolerance <= 10 % of pedal travel,
...). These are WARNINGS only: they are shown in red and listed before saving, and the
user decides whether to save anyway. Only a field that is not a number, or a locked
file, stops a save.

    python tools/throttle_map_editor.py             # open the editor
    python tools/throttle_map_editor.py --selftest  # check everything reads and writes back unchanged

Needs matplotlib (pip install matplotlib); tkinter comes with Python.
After saving: rebuild and flash the firmware.

APPS calibration: "Ligar VCU", then "Calibrar APPS" measures APPS1 with the pedal fully
pressed and released and writes APPS_MIN_BITS / APPS_MAX_BITS in APPS.h. Then rebuild and
flash from CubeIDE.

"Guardar config" / "Carregar config": the whole setup (map + every setting) in a JSON .cfg
file, in tools/configs by default. Loading fills the editor; "Gravar" writes it to the firmware.

Map units in the editor: accelerator and current in %, speed in km/h.
Map units in the file: per mille (0..1000 / -1000..1000), km/h.
Current > 0 = drive (SetRelCurrent), < 0 = regen (SetRelBrakeCurrent), 0 = coast.
"""

import contextlib
import json
import re
import sys
import time
from collections import deque, namedtuple
from itertools import pairwise
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from vcu_live import VcuLive

ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = ROOT / "Core" / "Inc" / "throttle_map_data.h"
CONFIG_DIR = Path(__file__).resolve().parent / "configs"  # saved setups (.cfg, JSON)

TEMPLATE = """\
/*
 * throttle_map_data.h - GENERATED by tools/throttle_map_editor.py
 * Edit with the tool (python tools/throttle_map_editor.py), then rebuild the firmware.
 *
 * throttle_map[speed][apps]: relative current, per mille of the inverter maximum
 *   > 0 = drive (SetRelCurrent), < 0 = regen (SetRelBrakeCurrent), 0 = coast
 * The VCU interpolates between points (throttle_map.c). Only included by throttle_map.c.
 */
#ifndef THROTTLE_MAP_DATA_H
#define THROTTLE_MAP_DATA_H

#include <stdint.h>

#define THROTTLE_MAP_APPS_POINTS  {na}
#define THROTTLE_MAP_SPEED_POINTS {ns}

// Accelerator axis (per mille of pedal travel)
static const uint16_t throttle_map_apps_axis[THROTTLE_MAP_APPS_POINTS] = {{
    {apps}
}};

// Vehicle speed axis (km/h)
static const uint16_t throttle_map_speed_axis[THROTTLE_MAP_SPEED_POINTS] = {{
    {speed}
}};

// Relative current (per mille), one row per speed, one column per accelerator point
static const int16_t throttle_map[THROTTLE_MAP_SPEED_POINTS][THROTTLE_MAP_APPS_POINTS] = {{
{rows}
}};

#endif  // THROTTLE_MAP_DATA_H
"""


# ============================ MAP FILE FORMAT ============================


def read_data(path=DATA_FILE):
    """Return (apps_axis, speed_axis, table[speed][apps]) from the .h file."""
    text = re.sub(r"/\*.*?\*/|//[^\n]*", "", path.read_text(), flags=re.DOTALL)
    arrays = {
        name: [int(n) for n in re.findall(r"-?\d+", body)]
        for name, body in re.findall(
            r"(\w+)\s*\[[^=]*=\s*\{(.*?)\};", text, flags=re.DOTALL
        )
    }
    apps, speed = arrays["throttle_map_apps_axis"], arrays["throttle_map_speed_axis"]
    flat = arrays["throttle_map"]
    if len(flat) != len(apps) * len(speed):
        raise ValueError(f"{path.name}: array sizes do not match the axes")
    table = [flat[i * len(apps) : (i + 1) * len(apps)] for i in range(len(speed))]
    return apps, speed, table


def validate(apps, speed, table):
    """Return a list of problems with the map (empty = OK to write)."""
    errors = []
    if len(apps) < 2 or len(speed) < 2:
        errors.append("Each axis needs at least 2 points")
    if any(b <= a for a, b in pairwise(apps)) or apps[0] < 0 or apps[-1] > 1000:
        errors.append("Accelerator axis must increase strictly, 0..100 %")
    if any(b <= a for a, b in pairwise(speed)) or speed[0] < 0:
        errors.append("Speed axis must increase strictly, from 0 km/h")
    if any(not -1000 <= v <= 1000 for row in table for v in row):
        errors.append("Current must be between -100 % and 100 %")
    return errors


def write_data(apps, speed, table, path=DATA_FILE):
    width = max(len(str(v)) for row in table for v in row)
    rows = "\n".join(
        "    {" + ", ".join(f"{v:{width}d}" for v in row) + f"}},  // {s} km/h"
        for s, row in zip(speed, table)
    )
    join = lambda values: ", ".join(str(v) for v in values)
    path.write_text(
        TEMPLATE.format(
            na=len(apps), ns=len(speed), apps=join(apps), speed=join(speed), rows=rows
        )
    )


def write_config(path, apps, speed, table, settings):
    """Whole setup -> JSON .cfg. Map in file units (per mille, km/h), settings {name: value}."""
    cfg = {"map": {"apps": apps, "speed": speed, "table": table}, "settings": settings}
    text = json.dumps(cfg, indent=1)
    text = re.sub(r"\[\s+([-\d.,\s]+?)\s+\]", lambda m: "[" + " ".join(m.group(1).split()) + "]", text)
    Path(path).write_text(text, encoding="utf-8")  # one line per list of numbers (map row)


def read_config(path):
    """JSON .cfg -> ((apps, speed, table), {setting: value}). Settings this editor does not know,
    or that are not numbers, are left out. Raises ValueError/KeyError/TypeError if it is no config."""
    cfg = json.loads(Path(path).read_text(encoding="utf-8"))
    apps, speed, table = cfg["map"]["apps"], cfg["map"]["speed"], cfg["map"]["table"]
    if len(table) != len(speed) or any(len(row) != len(apps) for row in table):
        raise ValueError("mapa: o tamanho da tabela nao bate com os eixos")
    settings = {name: value for name, value in cfg.get("settings", {}).items()
                if name in BY_NAME and isinstance(value, (int, float))}
    return (apps, speed, table), settings


# =============================== SETTINGS ===============================

DRIVING, SAFETY, TRACTION = "Conducao", "Calibracao / Seguranca", "Tracao / Vetorizacao"
TC, PAU, APPS_H, APPS_C, BSPD, CANU, TCTV = (
    "Core/Inc/throttle_control.h",
    "Core/Inc/pau_control.h",
    "Core/Inc/APPS.h",
    "Core/Src/APPS.c",
    "Core/Inc/bspd.h",
    "Core/Inc/CAN_utils.h",
    "Core/Inc/traction_control_torque_vectoring.h",
)

Setting = namedtuple("Setting", "tab file name kind lo hi label")
# Traction control (PI per rear wheel) and torque vectoring (feedforward), see the .h
TCTV_SETTINGS = [
    Setting(TRACTION, TCTV, *row)
    for row in [
        ("TRACTION_CONTROL_ENABLE", "bool", 0, 1, "Controlo de tracao ligado"),
        ("TORQUE_VECTORING_ENABLE", "bool", 0, 1, "Vetorizacao de binario ligada"),
        ("INVERTER_ID_REAR_LEFT", "int", 1, 2, "Inversor da roda traseira ESQUERDA (1 ou 2)"),
        ("VEHICLE_WHEELBASE_M", "float", 0.5, 3, "Entre-eixos (m)"),
        ("STEERING_RATIO", "float", 0.5, 50, "Relacao volante / roda (angulo volante / angulo roda)"),
        ("STEERING_SIGN", "float", -1, 1, "Sinal do volante (-1 se virar a esquerda da angulo negativo)"),
        ("STEERING_OFFSET_DEG", "float", -45, 45, "Angulo do volante com as rodas direitas (graus)"),
        ("SENSOR_TIMEOUT_MS", "int", 10, 1000, "Frame de sensor mais velha que isto = sensor em falta (ms)"),
        ("TRACTION_CONTROL_SLIP_TARGET", "float", 0, 1, "TC: patinagem permitida antes de cortar"),
        ("TRACTION_CONTROL_SPEED_MARGIN_KMH", "float", 0, 20, "TC: margem de velocidade (km/h)"),
        ("TRACTION_CONTROL_MINIMUM_SPEED_KMH", "float", 0, 50, "TC: desligado abaixo de (km/h, roda da frente)"),
        ("TRACTION_CONTROL_PROPORTIONAL_GAIN", "float", 0, 5, "TC: ganho P (corte por km/h)"),
        ("TRACTION_CONTROL_INTEGRAL_GAIN", "float", 0, 20, "TC: ganho I (corte por km/h por segundo)"),
        ("TRACTION_CONTROL_MINIMUM_TORQUE_FACTOR", "float", 0, 1, "TC: nunca menos que isto x o pedido"),
        ("TORQUE_VECTORING_GAIN_PER_G", "float", 0, 1, "TV: desvio de binario por g lateral"),
        ("TORQUE_VECTORING_MAXIMUM_SHIFT", "float", 0, 1, "TV: desvio maximo (0.15 = +-15 %)"),
        ("TORQUE_VECTORING_MINIMUM_SPEED_KMH", "float", 0, 100, "TV: desligado abaixo de (km/h)"),
        ("TORQUE_VECTORING_SHIFT_RATE_PER_S", "float", 0, 20, "TV: o desvio muda no maximo isto por segundo"),
    ]
]
SETTINGS = [
    Setting(DRIVING, TC, "THROTTLE_REGEN_ENABLE", "bool", 0, 1, "Regen ligada"),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_TORQUE_RISE_MAX_PCT_S",
        "int",
        0,
        10000,
        "Subida max. do binario (%/s, 0 = sem limite) - picos de corrente",
    ),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_REGEN_RAMP_UP_MS",
        "int",
        1,
        5000,
        "Regen: subida 0 -> 100 % (ms)",
    ),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_REGEN_RAMP_DOWN_MS",
        "int",
        1,
        5000,
        "Regen: descida 100 -> 0 % (ms)",
    ),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_REGEN_FADE_START_V",
        "int",
        0,
        1000,
        "Regen: reduz acima de (V, 0 = off)",
    ),
    Setting(
        DRIVING,
        TC,
        "THROTTLE_REGEN_CUTOFF_V",
        "int",
        0,
        1000,
        "Regen: corta a partir de (V, 0 = off)",
    ),
    Setting(
        DRIVING, TC, "THROTTLE_GEAR_RATIO", "float", 1, 50, "Relacao de transmissao"
    ),
    Setting(
        DRIVING, TC, "THROTTLE_WHEEL_RADIUS_M", "float", 0.1, 0.5, "Raio do pneu (m)"
    ),
    Setting(
        DRIVING,
        CANU,
        "MOTOR_POLE_PAIRS",
        "int",
        1,
        20,
        "Pares de polos do motor (ERPM / pares = rpm)",
    ),
    Setting(
        DRIVING,
        PAU,
        "PAU_CONTROL_ENABLE",
        "bool",
        0,
        1,
        "PAU (limite de potencia) ligado",
    ),
    Setting(
        DRIVING,
        PAU,
        "PAU_POWER_LIMIT_THRESHOLD_W",
        "int",
        0,
        200000,
        "PAU: comeca a limitar acima de (W)",
    ),
    Setting(
        DRIVING, PAU, "PAU_MAX_POWER_W", "int", 1, 200000, "PAU: potencia maxima (W)"
    ),
    Setting(
        DRIVING,
        PAU,
        "PAU_MAX_THROTTLE_AT_80KW_PERCENT",
        "int",
        0,
        100,
        "PAU: tracao permitida na potencia maxima (%)",
    ),
    Setting(SAFETY, APPS_H, "APPS_SINGLE_SENSOR", "bool", 0, 1, "So APPS1, SEM verificacao APPS1/APPS2 (so bancada)"),
    Setting(SAFETY, APPS_H, "APPS_MIN_BITS", "int", 0, 4095, "APPS1 a 0 % (bits)"),
    Setting(SAFETY, APPS_H, "APPS_MAX_BITS", "int", 0, 4095, "APPS1 a 100 % (bits)"),
    Setting(
        SAFETY,
        APPS_H,
        "APPS_TOLERANCE",
        "int",
        1,
        4095,
        "Discordancia max. APPS1/APPS2 (bits, <= 10 % do curso)",
    ),
    Setting(
        SAFETY,
        APPS_H,
        "APPS_HYSTERESIS_BITS",
        "int",
        0,
        20,
        "Histerese do pedal (bits)",
    ),
    Setting(
        SAFETY, APPS_H, "APPS2_OFFSET", "int", -10000, 4095, "APPS2 -> APPS1: offset (bits)"
    ),
    Setting(
        SAFETY,
        APPS_H,
        "APPS2_GAIN_X1000",
        "int",
        500,
        4000,
        "APPS2 -> APPS1: ganho x1000",
    ),
    Setting(
        SAFETY,
        APPS_H,
        "APPS_MA_WINDOW_SIZE",
        "int",
        1,
        20,
        "Media movel do APPS (amostras)",
    ),
    Setting(
        SAFETY,
        APPS_H,
        "MAX_APPS_TIMEOUT_MS",
        "int",
        10,
        500,
        "Sem frame APPS -> acelerador 0 (ms)",
    ),
    Setting(
        SAFETY,
        APPS_C,
        "APPS_TIMEOUT_MS",
        "int",
        1,
        1000,
        "Erro APPS persistente -> corte (ms)",
    ),
    Setting(
        SAFETY,
        BSPD,
        "BSPD_BRAKE_THRESHOLD",
        "float",
        1,
        200,
        "BSPD: travagem forte a partir de (bar)",
    ),
    Setting(
        SAFETY,
        BSPD,
        "BSPD_ACCEL_THRESHOLD",
        "int",
        0,
        1000,
        "BSPD: acelerador pressionado a partir de (0-1000)",
    ),
    Setting(
        SAFETY,
        BSPD,
        "BSPD_ACTIVATION_DELAY",
        "int",
        1,
        500,
        "BSPD: atraso a ativar (ms)",
    ),
    Setting(
        SAFETY,
        BSPD,
        "BSPD_DEACTIVATION_DELAY",
        "int",
        0,
        1000,
        "BSPD: atraso a desativar (ms)",
    ),
    Setting(
        SAFETY,
        CANU,
        "BRAKE_PRESSURE_THRESHOLD",
        "int",
        1,
        100,
        "R2D: pressao de travao minima (bar)",
    ),
    Setting(
        SAFETY,
        TC,
        "THROTTLE_SEND_BRAKE_LIMITS",
        "bool",
        0,
        1,
        "VCU envia limites de travagem aos inversores",
    ),
    Setting(
        SAFETY,
        TC,
        "THROTTLE_MAX_AC_BRAKE_CURRENT_A",
        "int",
        0,
        850,
        "Limite de travagem AC por inversor (A)",
    ),
    Setting(
        SAFETY,
        TC,
        "THROTTLE_MAX_DC_BRAKE_CURRENT_A",
        "int",
        0,
        850,
        "Limite de travagem DC por inversor (A)",
    ),
]
SETTINGS += TCTV_SETTINGS
BY_NAME = {s.name: s for s in SETTINGS}

# '#define NAME <number>[U|f]' followed only by spaces and an optional // comment
DEFINE_RE = r"^([ \t]*#define[ \t]+{name}[ \t]+)(-?\d+(?:\.\d+)?)([uUfF]?)(?=[ \t]*(?://[^\r\n]*)?\r?$)"


def read_file(rel):
    with open(
        ROOT / rel, encoding="utf-8", newline=""
    ) as f:  # newline="" keeps CRLF as is
        return f.read()


def find_define(text, name):
    """The match for '#define NAME <number>' if it is on exactly one plain line, else None."""
    matches = list(
        re.finditer(DEFINE_RE.format(name=re.escape(name)), text, flags=re.MULTILINE)
    )
    return matches[0] if len(matches) == 1 else None


def parse_value(setting, literal):
    """Number from the file, or None if it does not fit the setting's type."""
    try:
        value = float(literal) if setting.kind == "float" else int(literal)
    except ValueError:
        return None
    if setting.kind == "bool" and value not in (0, 1):
        return None
    return value


def read_settings():
    """{name: value}, with None for LOCKED settings. If any expected define of a file is
    missing, duplicated or not a plain number, all settings of that file are locked."""
    values = {}
    for rel in {s.file for s in SETTINGS}:
        names = [s.name for s in SETTINGS if s.file == rel]
        try:
            text = read_file(rel)
        except OSError:
            text = ""
        found = {}
        for name in names:
            match = find_define(text, name)
            found[name] = parse_value(BY_NAME[name], match.group(2)) if match else None
        file_ok = all(v is not None for v in found.values())
        values.update({name: (found[name] if file_ok else None) for name in names})
    return values


def check_settings(values):
    """[(file, message)] for out-of-range values and rule checks. None values are skipped."""
    errors = []
    for s in SETTINGS:
        v = values.get(s.name)
        if v is not None and not s.lo <= v <= s.hi:
            errors.append((s.file, f"{s.name} = {v:g} fora de {s.lo:g}..{s.hi:g}"))
    get = values.get
    lo, hi, tol = get("APPS_MIN_BITS"), get("APPS_MAX_BITS"), get("APPS_TOLERANCE")
    if None not in (lo, hi, tol):
        if hi <= lo:
            errors.append((APPS_H, "APPS_MIN_BITS tem de ser menor que APPS_MAX_BITS (senao o firmware nao compila)"))
        elif tol > (hi - lo) / 10:
            errors.append(
                (
                    APPS_H,
                    f"APPS_TOLERANCE > 10 % do curso do pedal ({(hi - lo) / 10:.0f} bits) - regra",
                )
            )
    if get("APPS_SINGLE_SENSOR") == 1:
        errors.append(
            (APPS_H, "APPS_SINGLE_SENSOR = 1: verificacao APPS1/APPS2 DESLIGADA - so bancada, nao e legal FS")
        )
    fade, cutoff = get("THROTTLE_REGEN_FADE_START_V"), get("THROTTLE_REGEN_CUTOFF_V")
    if None not in (fade, cutoff) and cutoff > 0 and fade >= cutoff:
        errors.append(
            (
                TC,
                "THROTTLE_REGEN_FADE_START_V tem de ser menor que THROTTLE_REGEN_CUTOFF_V (senao o firmware nao compila)",
            )
        )
    pau_lo, pau_hi = get("PAU_POWER_LIMIT_THRESHOLD_W"), get("PAU_MAX_POWER_W")
    if None not in (pau_lo, pau_hi) and pau_lo >= pau_hi:
        errors.append(
            (PAU, "PAU_POWER_LIMIT_THRESHOLD_W tem de ser menor que PAU_MAX_POWER_W (senao o firmware nao compila)")
        )
    return errors


APPS_CAL_MARGIN_BITS = 5  # 0 % = rest average + this, 100 % = full pedal average - this
APPS_CAL_SECONDS = 1.0  # each measurement (the pedal springs are too strong to hold it longer)
APPS_CAL_MAX_SPREAD = 6  # APPS1 moving more than this (bits) during a measurement -> warning


def apps_cal_defines(full, rest):
    """APPS1 readings with the pedal fully pressed / released -> (APPS_MIN_BITS, APPS_MAX_BITS,
    [warnings]). The margin keeps a released pedal at 0 % and a full pedal at 100 % even if
    the sensor drifts a few bits."""
    lo = round(sum(rest) / len(rest)) + APPS_CAL_MARGIN_BITS
    hi = round(sum(full) / len(full)) - APPS_CAL_MARGIN_BITS
    warnings = [f"{name}: APPS1 variou {min(v)}..{max(v)} bits - pedal a mexer ou sensor instavel"
                for name, v in (("A fundo", full), ("Repouso", rest)) if max(v) - min(v) > APPS_CAL_MAX_SPREAD]
    return lo, hi, warnings


def format_value(setting, value):
    if setting.kind != "float":
        return str(int(value))
    text = f"{value:.6g}"
    return text if ("." in text or "e" in text) else text + ".0"


def write_settings(new_values):
    """Write changed values in place, file by file. Returns (written_files, messages).
    Range and rule problems (check_settings) are only warnings and never stop the write.
    A file is skipped only if one of its #define lines no longer matches exactly once
    (the file changed since it was read) - writing it then would not be safe."""
    messages = []
    written = []
    for rel in sorted({BY_NAME[n].file for n in new_values}):
        text = read_file(rel)
        new_text = text
        for name, value in new_values.items():
            s = BY_NAME[name]
            if s.file != rel or value is None:
                continue
            match = find_define(new_text, name)
            if match is None:
                messages.append(f"{name}: linha do #define nao encontrada em {rel} - ficheiro nao gravado")
                new_text = None
                break
            if parse_value(s, match.group(2)) == value:
                continue
            literal = format_value(s, value)
            new_text = new_text[: match.start(2)] + literal + new_text[match.end(2) :]
        if new_text is not None and new_text != text:
            with open(ROOT / rel, "w", encoding="utf-8", newline="") as f:
                f.write(new_text)
            written.append(rel)
    return written, messages


def selftest():
    data = read_data()
    assert not validate(*data), validate(*data)
    tmp = DATA_FILE.with_suffix(".selftest.h")
    try:
        write_data(*data, path=tmp)
        assert read_data(tmp) == data, "map file does not read back the same"
    finally:
        tmp.unlink(missing_ok=True)

    values = read_settings()
    tmp = CONFIG_DIR.parent / "selftest.cfg"
    try:
        write_config(tmp, *data, values)
        assert read_config(tmp) == (data, values), "config does not read back the same"
    finally:
        tmp.unlink(missing_ok=True)
    locked = [n for n, v in values.items() if v is None]
    assert not locked, f"locked (define line not found): {locked}"
    # Writing the same values must not touch any file
    written, _ = write_settings(dict(values))
    assert not written, f"unchanged values rewrote {written}"
    # A define that is missing or duplicated must lock
    assert find_define("#define X 1\n", "APPS_MIN_BITS") is None
    assert (
        find_define(
            "#define APPS_MIN_BITS 1\n#define APPS_MIN_BITS 2\n", "APPS_MIN_BITS"
        )
        is None
    )
    assert find_define("#define APPS_MIN_BITS (1 + 2)\n", "APPS_MIN_BITS") is None
    match = find_define("#define APPS_MIN_BITS 1118U  // c\r\n", "APPS_MIN_BITS")
    assert match is not None and match.group(2) == "1118"
    assert axis_bracket([0, 10, 20], -5) == (0, 1, 0.0)
    assert axis_bracket([0, 10, 20], 25) == (1, 2, 1.0)
    assert axis_bracket([0, 10, 20], 15) == (1, 2, 0.5)
    assert axis_bracket([0, 10, 20], 10) == (0, 1, 1.0)
    assert cell_color(50) == "#ffacac" and cell_color(-50) == "#acacff" and cell_color(0) == "#ffffff"
    flat = {(r, c): 5.0 for r in range(1, 4) for c in range(1, 4)}
    assert smooth_cells(flat, flat) == flat, "smoothing a flat area must not change it"
    spike = {**dict.fromkeys(flat, 0.0), (2, 2): 16.0}
    assert smooth_cells(spike, {(2, 2)}) == {(2, 2): 4.0}  # centre weight 4 of 16
    assert smooth_cells(spike, {(1, 1)}) == {(1, 1): 16.0 / 9}  # corner: only 4 neighbours, weights 4+2+2+1
    assert apps_cal_defines([1485, 1486, 1487], [1330, 1331, 1332]) == (1331 + 5, 1486 - 5, [])
    assert len(apps_cal_defines([1400, 1486], [1330, 1331])[2]) == 1  # pedal not held at full
    problems = check_settings(values)
    print(
        f"OK - map {len(data[1])}x{len(data[0])}, {len(values)} settings found, none locked"
    )
    for _, msg in problems:
        print(f"  current value needs attention: {msg}")


# ================================== GUI ==================================

DEFAULT_VIEW = (
    18,
    -145,
)  # 3D view (elevation, azimuth): speed along the front, accelerator to the side
LIVE_TRAIL_POINTS = 8  # live trail length in the 3D view (1.6 s at the 200 ms poll), fades out
UNDO_STEPS = 100  # Ctrl+Z steps kept for the map
LIVE_LOST_TIMEOUT_S = 3  # reads failing this long (SWD noise) -> reopen the ST-LINK every 1 s until it works
LIVE_STRONG, LIVE_WEAK, LIVE_AXIS_BG = "#007a00", "#6fd66f", "#9be89b"  # live cursor colours in the table


def axis_bracket(axis, x):
    """Same as axis_find() in throttle_map.c: (lower index, upper index, fraction between them)."""
    if x <= axis[0]:
        return 0, 1, 0.0
    if x >= axis[-1]:
        return len(axis) - 2, len(axis) - 1, 1.0
    i = 0
    while x > axis[i + 1]:
        i += 1
    span = axis[i + 1] - axis[i]
    return i, i + 1, ((x - axis[i]) / span if span else 0.0)


def cell_color(percent, selected=False):
    """White at 0, red for drive, blue for regen, stronger with the value. Selected: darker."""
    shade = int(255 * (1 - 0.65 * min(abs(percent) / 100, 1)))
    rgb = (255, shade, shade) if percent > 0 else (shade, shade, 255) if percent < 0 else (255, 255, 255)
    if selected:
        rgb = tuple(v * 3 // 4 for v in rgb)
    return "#%02x%02x%02x" % rgb


def smooth_cells(values, cells):
    """{(row, col): value} -> new values for `cells`: weighted average with the 3x3 neighbours
    (1-2-1 kernel, centre x4), like TunerStudio "Smooth Cells". Neighbours outside the table
    are left out; cells not in `cells` are read but never changed."""
    kernel = {(dr, dc): (2 - abs(dr)) * (2 - abs(dc)) for dr in (-1, 0, 1) for dc in (-1, 0, 1)}
    new = {}
    for r, c in cells:
        near = [(w, values[r + dr, c + dc]) for (dr, dc), w in kernel.items() if (r + dr, c + dc) in values]
        new[r, c] = sum(w * v for w, v in near) / sum(w for w, _ in near)
    return new


def run_gui():
    import tkinter as tk
    from tkinter import filedialog, messagebox, ttk
    from typing import cast

    import numpy as np
    from matplotlib.artist import Artist
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
    from matplotlib.figure import Figure
    from mpl_toolkits.mplot3d import Axes3D
    from mpl_toolkits.mplot3d.art3d import Line3DCollection

    root = tk.Tk()
    root.title("VCU - mapa do acelerador e configuracao")

    bar = tk.Frame(root)
    bar.pack(fill="x", padx=4, pady=4)
    tabs = ttk.Notebook(root)
    tabs.pack(fill="both", expand=True)
    map_tab = tk.Frame(tabs)
    tabs.add(map_tab, text="Mapa")
    setting_tabs = {
        DRIVING: tk.Frame(tabs, padx=8, pady=8),
        SAFETY: tk.Frame(tabs, padx=8, pady=8),
        TRACTION: tk.Frame(tabs, padx=8, pady=8),
    }
    for name, frame in setting_tabs.items():
        tabs.add(frame, text=name)

    # ------------------------------- Map tab -------------------------------
    map_tools = tk.Frame(map_tab)
    map_tools.pack(fill="x", padx=4, pady=(4, 0))
    table_frame = tk.Frame(map_tab)
    table_frame.pack(padx=4, pady=4)

    fig = Figure(figsize=(11, 5.5))
    ax3d = cast(Axes3D, fig.add_subplot(1, 1, 1, projection="3d"))
    ax3d.view_init(*DEFAULT_VIEW)
    bottom = tk.Frame(map_tab)
    bottom.pack(fill="both", expand=True)
    live_frame = tk.LabelFrame(bottom, text="VCU ao vivo (ST-LINK)", padx=6, pady=4)
    live_frame.pack(side="right", fill="y", padx=4, pady=4)
    tk.Label(live_frame, text="Carrega em 'Ligar VCU'\n(CubeIDE fora de debug)", fg="gray").pack()
    canvas = FigureCanvasTkAgg(fig, master=bottom)
    canvas.get_tk_widget().pack(side="left", fill="both", expand=True)

    entries = {}  # (row, col) -> Entry; row 0 = accelerator axis, col 0 = speed axis
    cell_of = {}  # Entry -> (row, col), for the cell under the mouse while dragging
    grid_size = {"rows": range(0), "cols": range(0)}
    # Selected map cells (darker in the table, yellow dots in the 3D view); anchor = where the
    # click / drag / Shift+click selection starts
    selection: set[tuple[int, int]] = set()
    anchor: tuple[int, int] | None = None
    marker: Artist | None = None
    press_start: tuple[float, float] | None = None
    # Live link to the VCU (tools/vcu_live.py): green dot + highlighted cell = operating point
    live: VcuLive | None = None
    live_marker: Artist | None = None
    live_trail_line: Artist | None = None
    live_trail: deque[tuple[float, float, float]] = deque(maxlen=LIVE_TRAIL_POINTS)
    live_marked: dict[tuple[int, int], tuple[str, str | None]] = {}  # cell -> (border colour, axis bg) to restore
    live_poll_job: str | None = None  # pending poll, cancelled on disconnect so two loops never run
    live_failing_since: float | None = None  # time.monotonic() of the first failed read in a row
    live_labels: dict[str, tk.Label] = {}
    # Undo (Ctrl+Z): the map texts as last committed (Enter, leaving a cell, the buttons) and
    # the committed maps before it
    committed: dict[tuple[int, int], str] = {}
    undo_stack: deque[dict[tuple[int, int], str]] = deque(maxlen=UNDO_STEPS)

    def collect_map():
        """Read the grid back into file units. Raises ValueError on a bad number."""
        rows, cols = grid_size["rows"], grid_size["cols"]
        apps = [round(float(entries[0, c].get()) * 10) for c in cols]
        speed = [round(float(entries[r, 0].get())) for r in rows]
        table = [[round(float(entries[r, c].get()) * 10) for c in cols] for r in rows]
        return apps, speed, table

    def refresh_map(_event=None):
        nonlocal marker, live_marker, live_trail_line, committed
        try:
            apps, speed, table = collect_map()
        except ValueError:
            status.config(text="Valor invalido numa celula do mapa", fg="red")
            return
        texts = {cell: e.get() for cell, e in entries.items()}
        if committed and texts != committed:
            undo_stack.append(committed)
        committed = texts
        paint_cells(table)
        elev, azim = ax3d.elev, ax3d.azim
        ax3d.clear()
        ax3d.computed_zorder = (
            False  # draw by zorder, so the selection dot stays on top of the surface
        )
        x, y = np.meshgrid([a / 10 for a in apps], speed)
        ax3d.plot_surface(
            x,
            y,
            np.array(table) / 10,
            cmap="coolwarm",
            vmin=-100,
            vmax=100,
            edgecolor="k",
            linewidth=0.3,
        )
        ax3d.set_xlabel("Acelerador (%)")
        ax3d.set_ylabel("Velocidade (km/h)")
        ax3d.set_zlabel("Corrente (%)")
        ax3d.set_zlim(-100, 100)
        ax3d.view_init(elev, azim)
        marker = None  # cleared with the axes
        live_marker = live_trail_line = None  # redrawn by the next live poll
        draw_marker(apps, speed, table)
        fig.tight_layout()
        canvas.draw_idle()

    def paint_cells(table):
        for r in grid_size["rows"]:
            for c in grid_size["cols"]:
                entries[r, c].config(bg=cell_color(table[r - 1][c - 1] / 10, (r, c) in selection))

    # --- Link between the 3D view and the table ---
    def draw_marker(apps, speed, table):
        nonlocal marker
        if marker is not None:
            marker.remove()
            marker = None
        cells = sorted(selection)
        if not cells:
            return
        (marker,) = ax3d.plot(
            [apps[c - 1] / 10 for _, c in cells],
            [speed[r - 1] for r, _ in cells],
            [table[r - 1][c - 1] / 10 for r, c in cells],
            linestyle="none",
            marker="o",
            markersize=10 if len(cells) == 1 else 6,
            markerfacecolor="yellow",
            markeredgecolor="black",
            markeredgewidth=1.5,
            zorder=10,
        )
        if len(cells) == 1:
            r, c = cells[0]
            text = f"Celula: {speed[r - 1]} km/h, acelerador {apps[c - 1] / 10:g} % -> {table[r - 1][c - 1] / 10:g} %"
        else:
            text = f"{len(cells)} celulas selecionadas"
        status.config(text=text, fg="black")

    def set_selection(cells):
        if cells == selection:
            return
        selection.clear()
        selection.update(cells)
        try:
            data = collect_map()
        except ValueError:
            return
        paint_cells(data[2])
        draw_marker(*data)
        canvas.draw_idle()

    def select_rect(corner):
        """Select the rectangle from the anchor to `corner` (both included)."""
        (r0, c0), (r1, c1) = anchor, corner
        set_selection({(r, c) for r in range(min(r0, r1), max(r0, r1) + 1)
                       for c in range(min(c0, c1), max(c0, c1) + 1)})

    def on_cell_click(event, row, col):
        nonlocal anchor
        if event.state & 0x0001 and anchor is not None:  # Shift: extend from the anchor
            select_rect((row, col))
        else:
            anchor = (row, col)
            set_selection({(row, col)})
        if root.focus_get() is not entries[row, col]:  # not a 2nd click to place the cursor
            root.after_idle(select_focused_text)

    def select_focused_text():
        """Typing replaces the value of the focused cell (Shift+click keeps the focus where it was)."""
        focused = root.focus_get()
        if focused in cell_of:
            focused.select_range(0, "end")

    def on_cell_drag(event):
        cell = cell_of.get(root.winfo_containing(event.x_root, event.y_root))
        if anchor is not None and cell is not None:
            select_rect(cell)
            root.after_idle(select_focused_text)

    def on_cell_enter(row, col):
        """Enter: with several cells selected, all of them get the value typed in this one."""
        if len(selection) < 2 or (row, col) not in selection:
            refresh_map()
            return
        try:
            value = float(entries[row, col].get())
        except ValueError:
            status.config(text="Valor invalido", fg="red")
            return
        change_selected(lambda _values: dict.fromkeys(selection, value))

    def undo(_event=None):
        """Ctrl+Z on the map tab: first drops a value being typed, then steps back one change."""
        nonlocal committed
        if tabs.select() != str(map_tab):
            return None
        if {cell: e.get() for cell, e in entries.items()} != committed:
            target = committed
        elif undo_stack:
            target = undo_stack.pop()
        else:
            status.config(text="Nada para desfazer", fg="black")
            return "break"
        for cell, text in target.items():
            entries[cell].delete(0, "end")
            entries[cell].insert(0, text)
        committed = target
        refresh_map()
        status.config(text=f"Desfeito (Ctrl+Z) - mais {len(undo_stack)} para tras", fg="black")
        return "break"

    root.bind_all("<Control-z>", undo)
    root.bind_all("<Control-Z>", undo)

    def show_selection(row, col):
        """A cell got the focus (keyboard or click): select it, unless it is already selected."""
        nonlocal anchor
        if (row, col) not in selection:
            anchor = (row, col)
            set_selection({(row, col)})

    def change_selected(new_values):
        """new_values({cell: %}) -> {cell: new %} for the selected cells; written and redrawn."""
        if not selection:
            status.config(text="Seleciona celulas do mapa primeiro (arrastar ou Shift+clique)", fg="red")
            return
        try:
            values = {(r, c): float(entries[r, c].get()) for r in grid_size["rows"] for c in grid_size["cols"]}
            new = new_values(values)
        except ValueError:
            status.config(text="Valor invalido numa celula do mapa ou no passo", fg="red")
            return
        for cell, value in new.items():
            entries[cell].delete(0, "end")
            entries[cell].insert(0, f"{min(max(round(value, 1), -100.0), 100.0):g}")
        refresh_map()

    step = tk.StringVar(value="1")

    def nudge(sign):
        change_selected(lambda values: {cell: values[cell] + sign * float(step.get()) for cell in selection})

    tk.Button(map_tools, text="-", width=3, command=lambda: nudge(-1)).pack(side="left")
    tk.Button(map_tools, text="+", width=3, command=lambda: nudge(+1)).pack(side="left", padx=(2, 4))
    tk.Label(map_tools, text="passo").pack(side="left")
    tk.Entry(map_tools, textvariable=step, width=5, justify="right").pack(side="left")
    tk.Label(map_tools, text="%").pack(side="left", padx=(0, 12))
    tk.Button(map_tools, text="Suavizar", command=lambda: change_selected(
        lambda values: smooth_cells(values, selection))).pack(side="left")
    tk.Label(map_tools, text="Selecionar: arrastar ou Shift+clique.  Escrever + Enter: todas as selecionadas.  "
                             "Ctrl+Z: desfazer", fg="gray").pack(
        side="left", padx=12)

    def on_press(event):
        nonlocal press_start
        press_start = (event.x, event.y) if event.inaxes is ax3d else None

    def on_release(event):
        """Click (not a rotation drag) on the 3D view: select the nearest point in the table."""
        start = press_start
        if (
            start is None
            or event.inaxes is not ax3d
            or abs(event.x - start[0]) > 3
            or abs(event.y - start[1]) > 3
        ):
            return
        try:
            apps, speed, table = collect_map()
        except ValueError:
            return
        # Project every grid point to screen pixels and take the closest one
        cells = [(r, c) for r in grid_size["rows"] for c in grid_size["cols"]]
        points = np.array(
            [
                [apps[c - 1] / 10, speed[r - 1], table[r - 1][c - 1] / 10, 1.0]
                for r, c in cells
            ]
        )
        projected = points @ ax3d.get_proj().T
        screen = ax3d.transData.transform(projected[:, :2] / projected[:, 3:4])
        distances = np.hypot(screen[:, 0] - event.x, screen[:, 1] - event.y)
        nearest = int(np.argmin(distances))
        if distances[nearest] <= 25:  # pixels
            move(*cells[nearest])

    canvas.mpl_connect("button_press_event", on_press)
    canvas.mpl_connect("button_release_event", on_release)

    def move(row, col):
        if (row, col) in entries:
            entries[row, col].focus_set()
            entries[row, col].select_range(0, "end")

    def add_cell(row, col, value, axis=False):
        # Grid is shifted by one row/column to make room for the axis titles
        e = tk.Entry(
            table_frame,
            width=6,
            justify="right",
            bg="#e4e4e4" if axis else "white",
            font=("Consolas", 9, "bold" if axis else "normal"),
            # Fixed 2 px border in the background colour: the live cursor only recolours it,
            # so the table never changes size while it moves
            highlightthickness=2,
            highlightbackground=table_frame.cget("bg"),
            highlightcolor=table_frame.cget("bg"),
        )
        e.insert(0, value)
        e.grid(row=row + 1, column=col + 1)
        e.bind("<Return>", refresh_map if axis else lambda _e: on_cell_enter(row, col))
        e.bind("<FocusOut>", refresh_map)
        e.bind("<Up>", lambda _e: move(row - 1, col))
        e.bind("<Down>", lambda _e: move(row + 1, col))
        if not axis:
            e.bind("<FocusIn>", lambda _e: show_selection(row, col))
            e.bind("<Button-1>", lambda ev: on_cell_click(ev, row, col), add="+")
            e.bind("<B1-Motion>", on_cell_drag, add="+")
            cell_of[e] = (row, col)
        entries[row, col] = e

    def load_map(data=None):
        """Build the table from `data` (apps, speed, table), or from the map file."""
        nonlocal anchor, committed
        apps, speed, table = data or read_data()
        for widget in table_frame.winfo_children():
            widget.destroy()
        entries.clear()
        cell_of.clear()
        selection.clear()
        anchor = None
        committed = {}
        undo_stack.clear()
        grid_size["rows"] = range(1, len(speed) + 1)
        grid_size["cols"] = range(1, len(apps) + 1)
        title = ("Arial", 10, "bold")
        tk.Label(table_frame, text="ACELERADOR (%)", font=title).grid(
            row=0, column=2, columnspan=len(apps), sticky="w"
        )
        tk.Label(table_frame, text="\n".join("VELOCIDADE") + "\n\nkm", font=title).grid(
            row=2, column=0, rowspan=len(speed), padx=(0, 4)
        )
        tk.Label(table_frame, text="km/h \\ %").grid(row=1, column=1)
        for c, a in zip(grid_size["cols"], apps):
            add_cell(0, c, f"{a / 10:g}", axis=True)
        for r, s, row in zip(grid_size["rows"], speed, table):
            add_cell(r, 0, str(s), axis=True)
            for c, v in zip(grid_size["cols"], row):
                add_cell(r, c, f"{v / 10:g}")
        refresh_map()

    # ---------------------------- Settings tabs ----------------------------
    fields = {}  # name -> (var, widget, note_label)
    loaded = {}  # name -> value read from the file (None = locked)
    unlock = tk.IntVar(value=0)

    def field_value(name):
        var = fields[name][0]
        return float(var.get()) if BY_NAME[name].kind == "float" else int(var.get())

    def apply_states():
        for name, (var, widget, note) in fields.items():
            s = BY_NAME[name]
            editable = loaded.get(name) is not None and (
                s.tab != SAFETY or unlock.get()
            )
            widget.config(state="normal" if editable else "disabled")

    def mark_settings(_event=None):
        """Red note on out-of-range / rule problems, grey note otherwise."""
        values = {}
        for name in fields:
            if loaded.get(name) is None:
                continue
            try:
                values[name] = field_value(name)
            except ValueError:
                fields[name][2].config(text="numero invalido", fg="red")
        problems = {}
        for rel, msg in check_settings(values):
            for name in re.findall(r"[A-Z][A-Z0-9_]{3,}", msg):
                problems.setdefault(name, msg)
        for name, (var, widget, note) in fields.items():
            if loaded.get(name) is None:
                note.config(text="#define nao encontrado - BLOQUEADO", fg="red")
            elif name in values:
                s = BY_NAME[name]
                msg = problems.get(name)
                note.config(
                    text=msg if msg else f"{s.lo:g}..{s.hi:g}",
                    fg="red" if msg else "gray",
                )

    tk.Checkbutton(
        setting_tabs[SAFETY],
        text="Desbloquear edicao (valores de seguranca)",
        variable=unlock,
        command=apply_states,
        fg="red",
    ).grid(row=0, column=0, columnspan=4, sticky="w", pady=(0, 8))
    row_of = {DRIVING: 0, SAFETY: 1, TRACTION: 0}
    for s in SETTINGS:
        frame = setting_tabs[s.tab]
        r = row_of[s.tab]
        row_of[s.tab] += 1
        tk.Label(frame, text=s.label, anchor="w").grid(
            row=r, column=0, sticky="w", padx=(0, 8)
        )
        var = tk.IntVar() if s.kind == "bool" else tk.StringVar()
        if s.kind == "bool":
            widget = tk.Checkbutton(frame, variable=var, command=mark_settings)
        else:
            widget = tk.Entry(frame, textvariable=var, width=12, justify="right")
            widget.bind("<Return>", mark_settings)
            widget.bind("<FocusOut>", mark_settings)
        widget.grid(row=r, column=1, sticky="w")
        tk.Label(frame, text=f"{s.name}  ({Path(s.file).name})", fg="gray").grid(
            row=r, column=2, sticky="w", padx=8
        )
        note = tk.Label(frame, anchor="w")
        note.grid(row=r, column=3, sticky="w")
        fields[s.name] = (var, widget, note)

    def load_settings():
        loaded.clear()
        loaded.update(read_settings())
        for name, (var, widget, note) in fields.items():
            value = loaded[name]
            if BY_NAME[name].kind == "bool":
                var.set(value or 0)
            else:
                var.set("" if value is None else f"{value:g}")
        apply_states()
        mark_settings()

    # ------------------------------- Buttons -------------------------------
    def load_all():
        try:
            load_map()
        except (OSError, KeyError, ValueError) as err:
            messagebox.showerror("Erro ao ler o mapa", str(err))
        load_settings()
        status.config(text="Lido", fg="black")

    def save_all():
        # 1. Read everything. Only a cell that is not a number stops the save: nothing to write.
        try:
            data = collect_map()
        except ValueError:
            messagebox.showerror("Nao gravado", "Mapa: ha uma celula que nao e numero")
            return
        new_values = {}
        not_numbers = []
        for name in fields:
            s = BY_NAME[name]
            if loaded.get(name) is None or (s.tab == SAFETY and not unlock.get()):
                continue  # locked (#define not found) or safety tab not unlocked
            try:
                new_values[name] = field_value(name)
            except ValueError:
                not_numbers.append(name)
        if not_numbers:
            messagebox.showerror("Nao gravado", "Valor que nao e numero: " + ", ".join(not_numbers))
            return

        # 2. Rules and ranges are warnings only: show them all, the user decides
        warnings = [f"Mapa: {e}" for e in validate(*data)] + [m for _, m in check_settings(new_values)]
        if warnings and not messagebox.askyesno(
            "Avisos", "\n".join(f"- {w}" for w in warnings) + "\n\nGravar mesmo assim?", icon="warning"
        ):
            status.config(text="Nao gravado", fg="black")
            return

        # 3. Write what changed
        written: list[str] = []
        try:
            unchanged = data == read_data()
        except (OSError, KeyError, ValueError):
            unchanged = False  # Unreadable file: rewrite it from the editor values
        if not unchanged:
            write_data(*data)
            written.append(str(DATA_FILE.relative_to(ROOT)))
        files, problems = write_settings(new_values)
        written += files
        load_settings()
        mark_settings()
        if problems:
            messagebox.showwarning("Nao foi tudo gravado", "\n".join(problems))
        status.config(
            text=(
                f"Gravado {time.strftime('%H:%M:%S')}: {', '.join(written)} - compila e grava o firmware"
                if written
                else "Nada alterado para gravar"
            ),
            fg="green" if written and not problems else "black",
        )

    tk.Button(bar, text="Gravar", width=10, command=save_all).pack(side="left")
    tk.Button(bar, text="Recarregar", width=10, command=load_all).pack(
        side="left", padx=4
    )

    cfg_types = [("Config", "*.cfg")]

    def save_config():
        try:
            data = collect_map()
            settings = {name: field_value(name) for name in fields if loaded.get(name) is not None}
        except ValueError:
            messagebox.showerror("Config nao guardada", "Ha um valor que nao e numero (mapa ou definicoes)")
            return
        CONFIG_DIR.mkdir(exist_ok=True)
        path = filedialog.asksaveasfilename(parent=root, initialdir=CONFIG_DIR, defaultextension=".cfg",
                                            filetypes=cfg_types)
        if path:
            write_config(path, *data, settings)
            status.config(text=f"Config guardada: {Path(path).name}", fg="green")

    def load_config():
        CONFIG_DIR.mkdir(exist_ok=True)
        path = filedialog.askopenfilename(parent=root, initialdir=CONFIG_DIR, filetypes=cfg_types)
        if not path:
            return
        try:
            data, settings = read_config(path)
        except (OSError, ValueError, KeyError, TypeError) as err:
            messagebox.showerror("Config nao carregada", f"{Path(path).name}: {err}")
            return
        load_map(data)
        for name, value in settings.items():
            if loaded.get(name) is not None:  # locked settings (#define not found) stay as they are
                fields[name][0].set(int(value) if BY_NAME[name].kind == "bool" else f"{value:g}")
        mark_settings()
        status.config(text=f"Carregada {Path(path).name} - 'Gravar' escreve no firmware "
                           "(Calibracao/Seguranca: desbloquear primeiro)", fg="green")

    tk.Button(bar, text="Guardar config", command=save_config).pack(side="left")
    tk.Button(bar, text="Carregar config", command=load_config).pack(side="left", padx=4)

    def reset_view():
        ax3d.view_init(*DEFAULT_VIEW)
        canvas.draw_idle()

    tk.Button(bar, text="Vista 3D default", command=reset_view).pack(side="left")

    # ------------------------- Live link to the VCU -------------------------
    def mark_live(cells):
        """cells: {(row, col): 'strong' | 'weak' | 'axis'}. Undoes the previous marks first."""
        if cells.keys() == live_marked.keys():
            return
        for cell, (border, axis_bg) in live_marked.items():
            if cell in entries:
                entries[cell].config(highlightbackground=border, highlightcolor=border)
                if axis_bg is not None:
                    entries[cell].config(bg=axis_bg)
        live_marked.clear()
        for cell, style in cells.items():
            if cell not in entries:
                continue
            e = entries[cell]
            live_marked[cell] = (e.cget("highlightbackground"), e.cget("bg") if style == "axis" else None)
            if style == "axis":
                e.config(bg=LIVE_AXIS_BG)
            else:
                color = LIVE_STRONG if style == "strong" else LIVE_WEAK
                e.config(highlightbackground=color, highlightcolor=color)

    def draw_live(values):
        """ECU-style live cursor: green dot + trail in 3D; interpolation box and axes in the table."""
        nonlocal live_marker, live_trail_line
        for artist in (live_marker, live_trail_line):
            if artist is not None:
                artist.remove()
        live_marker = live_trail_line = None
        pedal = values.get("throttle.pedal_1000")
        speed_now = values.get("throttle.speed_kmh")
        map_now = values.get("throttle.map_1000")
        if pedal is None or speed_now is None or map_now is None:
            return
        point = (pedal / 10, speed_now, map_now / 10)
        live_trail.append(point)
        if len(live_trail) >= 2:
            # Fading trail: oldest segment almost transparent, newest strong
            points = list(live_trail)
            segments = [[points[k], points[k + 1]] for k in range(len(points) - 1)]
            colors = [(0.0, 0.6, 0.0, 0.1 + 0.8 * (k + 1) / len(segments)) for k in range(len(segments))]
            live_trail_line = Line3DCollection(segments, colors=colors, linewidths=1.5, zorder=10)
            ax3d.add_collection3d(live_trail_line)
        (live_marker,) = ax3d.plot([point[0]], [point[1]], [point[2]], linestyle="none", marker="o",
                                   markersize=11, markerfacecolor="#00d000", markeredgecolor="black",
                                   markeredgewidth=1.5, zorder=11)
        try:
            apps, speed, _ = collect_map()
        except ValueError:
            apps = speed = None
        if apps and speed:
            # The 4 cells the VCU interpolates between (same as throttle_map.c), heaviest one strongest
            c0, c1, fa = axis_bracket(apps, pedal)
            r0, r1, fs = axis_bracket(speed, speed_now)
            weights = {(r0 + 1, c0 + 1): (1 - fs) * (1 - fa), (r0 + 1, c1 + 1): (1 - fs) * fa,
                       (r1 + 1, c0 + 1): fs * (1 - fa), (r1 + 1, c1 + 1): fs * fa}
            heaviest = max(weights, key=lambda cell: weights[cell])
            cells = {cell: ("strong" if cell == heaviest else "weak") for cell in weights}
            cells.update({(0, c0 + 1): "axis", (0, c1 + 1): "axis", (r0 + 1, 0): "axis", (r1 + 1, 0): "axis"})
            mark_live(cells)
        canvas.draw_idle()

    def poll_live():
        nonlocal live_poll_job, live_failing_since
        live_poll_job = None
        link = live
        if link is None:
            return
        try:
            values = link.read()
        except Exception:  # noqa: BLE001 - SWD noise, probe unplugged, USB/pyocd error: retry, not a crash
            # Noise on SWCLK/SWDIO (inverters) makes single reads fail: keep the last values and retry
            now = time.monotonic()
            live_failing_since = live_failing_since or now
            if now - live_failing_since >= LIVE_LOST_TIMEOUT_S:
                # Still failing: reopen the ST-LINK. With the inverters on it can drop off USB and
                # come back seconds later, so keep trying every second until "Desligar VCU".
                try:
                    link.close()
                    link.connect()
                    live_failing_since = None
                except Exception as err:  # noqa: BLE001 - any connect problem becomes a message
                    status.config(text=f"Sem ligacao a VCU ha {now - live_failing_since:.0f} s - a tentar de novo "
                                       f"('Desligar VCU' para parar): {str(err).splitlines()[0]}", fg="#c06000")
                    live_poll_job = root.after(1000, poll_live)
                    return
            status.config(text=f"Sem leitura da VCU ha {now - (live_failing_since or now):.1f} s "
                               "(ruido no SWD?) - a tentar...", fg="#c06000")
            live_poll_job = root.after(200, poll_live)
            return
        if live_failing_since is not None:
            live_failing_since = None
            status.config(text="Ligacao a VCU recuperada", fg="green")
        for v in link.variables:
            live_labels[v.expr].config(text=v.text(values[v.expr]))
        draw_live(values)
        live_poll_job = root.after(200, poll_live)

    def disconnect_live(message):
        nonlocal live, live_marker, live_trail_line, live_poll_job, live_failing_since
        live_failing_since = None
        if live_poll_job is not None:
            root.after_cancel(live_poll_job)
            live_poll_job = None
        link = live
        live = None
        if link is not None:
            with contextlib.suppress(Exception):  # probe may already be gone
                link.close()
        for artist in (live_marker, live_trail_line):
            if artist is not None:
                artist.remove()
        live_marker = live_trail_line = None
        live_trail.clear()
        canvas.draw_idle()
        mark_live({})
        live_button.config(text="Ligar VCU")
        status.config(text=message, fg="black")

    def toggle_live():
        nonlocal live
        if live is not None:
            disconnect_live("Desligado da VCU")
            return
        try:
            sys.path.insert(0, str(Path(__file__).resolve().parent))
            from vcu_live import VcuLive

            link = VcuLive()
            link.connect()
        except Exception as err:  # noqa: BLE001 - any connect problem becomes a message
            messagebox.showerror("VCU ao vivo", str(err))
            return
        live = link
        for widget in live_frame.winfo_children():
            widget.destroy()
        live_labels.clear()
        rows = (len(link.variables) + 1) // 2  # two columns: the full list does not fit the window height
        for i, v in enumerate(link.variables):
            column = 2 * (i // rows)
            tk.Label(live_frame, text=v.label, anchor="w").grid(row=i % rows, column=column, sticky="w",
                                                                padx=(12 if column else 0, 0))
            live_labels[v.expr] = tk.Label(live_frame, text="-", width=24 if v.kind == "enum" else 8, anchor="e",
                                           font=("Consolas", 10, "bold"))
            live_labels[v.expr].grid(row=i % rows, column=column + 1, sticky="e")
        for j, expr in enumerate(link.missing):
            tk.Label(live_frame, text=f"{expr}: nao existe no ELF", fg="gray").grid(
                row=rows + j, column=0, columnspan=4, sticky="w")
        live_button.config(text="Desligar VCU")
        status.config(text="Ligado a VCU (ST-LINK) - so leitura", fg="green")
        poll_live()

    live_button = tk.Button(bar, text="Ligar VCU", width=12, command=toggle_live)
    live_button.pack(side="left", padx=4)

    def calibrate_apps():
        """Pedal fully pressed, then released -> APPS_MIN_BITS / APPS_MAX_BITS written in APPS.h."""
        title = "Calibrar APPS"
        link = live
        if link is None:
            messagebox.showinfo(title, "Liga primeiro a VCU ('Ligar VCU').")
            return
        if loaded.get("APPS_MIN_BITS") is None or loaded.get("APPS_MAX_BITS") is None:
            messagebox.showerror(title, "APPS.h bloqueado (#define nao encontrado) - nada a gravar.")
            return
        steps = (("full", "1/2  Carrega o pedal A FUNDO, mantem, e carrega OK.\n\nMede durante 1 s."),
                 ("rest", "2/2  Larga o pedal (repouso) e carrega OK.\n\nMede durante 1 s."))
        samples = {}
        try:
            for step, text in steps:
                if not messagebox.askokcancel(title, text) or live is not link:
                    status.config(text="Calibracao APPS cancelada", fg="black")
                    return
                status.config(text="A medir o APPS1...", fg="black")
                root.update_idletasks()
                end = time.monotonic() + APPS_CAL_SECONDS
                samples[step] = [link.read()["apps_data.state.apps1_raw"]]
                while time.monotonic() < end:
                    samples[step].append(link.read()["apps_data.state.apps1_raw"])
        except Exception as err:  # noqa: BLE001 - probe unplugged, USB/pyocd error: message, not a crash
            disconnect_live(f"Ligacao a VCU perdida: {err}")
            return
        lo, hi, warnings = apps_cal_defines(samples["full"], samples["rest"])
        new_values = {"APPS_MIN_BITS": lo, "APPS_MAX_BITS": hi}
        warnings += [m for f, m in check_settings({**loaded, **new_values}) if f == APPS_H]
        full, rest = samples["full"], samples["rest"]
        text = (f"A fundo:  APPS1 {min(full)}..{max(full)}, media {round(sum(full) / len(full))}\n"
                f"Repouso:  APPS1 {min(rest)}..{max(rest)}, media {round(sum(rest) / len(rest))}\n\n"
                f"APPS_MIN_BITS  {loaded['APPS_MIN_BITS']:g} -> {lo}   (media repouso + {APPS_CAL_MARGIN_BITS})\n"
                f"APPS_MAX_BITS  {loaded['APPS_MAX_BITS']:g} -> {hi}   (media a fundo - {APPS_CAL_MARGIN_BITS})\n\n")
        if warnings:
            text += "ATENCAO:\n" + "\n".join(f"- {w}" for w in warnings) + "\n\n"
        text += "Gravar no APPS.h?"
        if not messagebox.askyesno(title, text, icon="warning" if warnings else "question"):
            status.config(text="Calibracao APPS nao gravada", fg="black")
            return
        _, problems = write_settings(new_values)
        if problems:
            messagebox.showerror(title, "\n".join(problems))
            return
        for name, value in new_values.items():  # only these two fields: other unsaved edits stay
            loaded[name] = value
            fields[name][0].set(str(value))
        mark_settings()
        status.config(text=f"APPS.h gravado: 0 % = {lo}, 100 % = {hi} bits - compila e grava o firmware no CubeIDE",
                      fg="green")

    tk.Button(bar, text="Calibrar APPS", command=calibrate_apps).pack(side="left", padx=2)

    def on_close():
        disconnect_live("")
        root.destroy()

    root.protocol("WM_DELETE_WINDOW", on_close)
    tk.Label(bar, text="Mapa: + tracao (vermelho), - regen (azul)").pack(
        side="left", padx=8
    )
    status = tk.Label(bar, anchor="e")
    status.pack(side="right")

    load_all()
    root.mainloop()


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        selftest()
    else:
        run_gui()
